### PR TITLE
New Job - Design help needed for an open source, free, charity based social platform

### PR DESCRIPTION
**Pull request by staticmanapp**
Dear human,

Here's a new entry for your approval. :tada:

Merge the pull request to accept it, or close it to send it away.

:heart: Your friend [Staticman](https://staticman.net) :muscle:

---
| Field        | Content                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      |
| ------------ | -------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- |
| status       | searching                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    |
| date_posted  | 2017-11-08                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   |
| layout       | jobs                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         |
| organization | Trekking for Charity                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         |
| org_url      | http://www.trekkingforcharity.org                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            |
| title        | Design help needed for an open source, free, charity based social platform                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   |
| role         | 'Logo design & branding', 'Web design', 'Interaction design'                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 |
| compensation | gratis                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       |
| description  | Trekking for Charity is a project to help people organise and run sponsored events like walks and bike rides.  I came up with the idea run a family member was doing a week long hike to raise money for charity, but was unable to keep people updated with things like their location and post updates to their feeds.  Another key issue is that they wasn't able to set up a plan, e.g. set up points on a map and detail when they planned to reach it.

Although I have had the idea for some time, it's only recently I have had some time to put into the project, and this is where I need some help.  I'm a web developer, who focuses on the Microsoft stack, but I have very little design skills.  I am hoping to find someone to help with all aspects of the design. From the initial UX to the page designs of the site and mobile apps.

I'm looking at this at being a real collaborative project and will look at taking any help given, and depending on what you want the door is open for a long term team member. |
| deliverables |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              |
| how_to_apply | andrew@trekkingforcharity.org,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               |
| tags         | logo, branding, UX design                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    |
| date         | 2017-11-08T12:54:24.839Z                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     |

### CODE REVIEW

**Comment by evalica** [comment]
is this OSS? the URL is not working and there is no link to the sources

**Comment by simonv3** [comment]
Since the URL isn't working I just assumed that the source hadn't even been started on. It does say it's open source in the job posting.

**Comment by elioqoshi** [comment]
I'd prefer some further elaboration from the author

**Comment by simonv3** [comment]
I've asked for elaboration on the job post http://opensourcedesign.net/jobs/jobs/2017-11-08-design-help-needed-for-an-open-source-free-charity-based-social-platform which is a comment thread here: https://discourse.opensourcedesign.net/t/jobs-design-help-needed-for-an-open-source-free-charity-based-social-platform/448

**Pull request merged**
