### PR TITLE
Tor Style Guide

### PR DESCRIPTION
**Pull request by ameellio**

### CODE REVIEW

**Comment by simonv3** [comment]
Looks awesome, thanks for the PR!

**Comment by elioqoshi** [comment]
Definitely interested in this :) Shooting an email tomorrow

**Comment by ei8fdb** [comment]
\0/ yay to @ameellio posting jobs!

**Comment by elioqoshi** [comment]
I talked with @ameellio and took this on, I had a videocall with her earlier and everything's settled and I'm starting work soon :)

**Comment by simonv3** [comment]
Awesome @elioqoshi, that's great to hear 👍

**Pull request merged**
