### PR TITLE
New Job - Improving the two webpages of a simple web interface to a metadata-removal tool

### PR DESCRIPTION
**Pull request by staticmanapp**
Dear human,

Here's a new entry for your approval. :tada:

Merge the pull request to accept it, or close it to send it away.

:heart: Your friend [Staticman](https://staticman.net) :muscle:

---
| Field        | Content                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    |
| ------------ | ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------ |
| status       | searching                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  |
| date_posted  | 2019-02-03                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 |
| layout       | jobs                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       |
| organization | mat2-web                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   |
| org_url      | https://0xacab.org/jvoisin/mat2-web                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        |
| title        | Improving the two webpages of a simple web interface to a metadata-removal tool                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            |
| role         | Web design                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 |
| compensation | gratis                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     |
| description  | Mat2 is an open-source [metadata]( https://en.wikipedia.org/wiki/Metadata ) removal tool. Currently the two main ways of using it are either the command line interface, of a file-browser extension. I recently wrote a web interface to make it more accessible to non-technical people (see the demo instance [here](https://mat2-web.dustri.org)), but it doesn't look super-pretty. Some journalist organizations already deployed their own private instance, but their users are complaining about the lack of prettiness and usability of it.

Since I don't know much about UX/accessibility, help would be more than welcome ♥ |
| deliverables |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            |
| how_to_apply | jvoisin (lead dev) <julien.voisin+mat2@dustri.org>,- https://dustri.org/b/mat2-for-the-web.html                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            |
| tags         | web, metadata, simple, privacy                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             |
| date         | 2019-02-03T13:57:13.856Z                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   |

### CODE REVIEW

**Comment by ei8fdb** [comment]
Hi Julien,

I hope this might be useful:

> Role: UI designer
> 
> Mat2 is an open-source metadata removal tool. It can be self-hosted to maintain privacy of the users files.
>
> Currently the two main ways of using it are either the command line interface, or using the web 
> interface.

> We created a web interface to make it more accessible to non-technical people (see the demo 
> instance here). Some journalist organizations (who have already deployed their own private instance) 
> gave feedback about its usability and the visual design.
>
> We need design input to improve:
> 
> - the usability of the tool
> - the UI of the "metadata removed" interface to make it clear the types of metadata that were removed
> - carry out some usability tests to make sure the user understands what has happened

What do you think?

**Comment by ei8fdb** [comment]
Email sent:

> Hi Julien,
> 
> I've made some comments on the job posting you made:
> 
> https://github.com/opensourcedesign/jobs/pull/377
> 
> If you think they are helpful, I'll edit the original and we'll then
> post it.
> 
> Thanks,
> Bernard
>

**Comment by jvoisin** [comment]
The two main ways of using mat2 are either via the command line, or a **file browser** (and not a web browser) extension ;)

Otherwise, I do like your improvements ♥

**Comment by ei8fdb** [comment]
@jvoisin ah apologies, I tried out the demo version (in the link above) and it was a web interface.

So to make sure I have it right: you're looking for design input to work on 1) the commandline interface and 2) what exactly?

**Comment by jvoisin** [comment]
I'm looking for design input on the web interface only.

I wrote the web interface because
- the command-line isn't super usable for non-tech people
- not everyone is using Linux+GNOME+Nautilus which are requirements for using the file-browser extension.

Sorry for not being super-duper-clear :/

**Pull request merged**
