### PR TITLE
2016-06-13-openSUSE_101_shirt.md

### PR DESCRIPTION
**Pull request by ChrisBr**

### CODE REVIEW

**Comment by simonv3** [comment]
Looks awesome @ChrisBr, thanks for submitting the job!

You can see it here: http://opensourcedesign.net/jobs/jobs/2016-06-13-openSUSE_101_shirt

**Comment by elioqoshi** [comment]
I was planning to take on this, but if someone else would chime in, that would be appreciated!
#NoMonopoly

**Comment by simonv3** [comment]
Thanks for being considerate about it @elioqoshi. That's pretty awesome of you. It's been 3 days though, people have had some time to respond if they wanted to take it on?

Maybe this is something we should specify in our page we've been talking about in issue #91. Maybe a maximum wait period or similar?

I'm becoming more and more firmly a believer in "if you're the one that wants to do it, do it."

**Comment by gillisig** [comment]
What @simonv3 said! :) Go for it

**Pull request merged**
