### PR TITLE
Add Staticman data

### PR DESCRIPTION
**Pull request by staticmanapp**
Dear human,

Here's a new entry for your approval. :tada:

Merge the pull request to accept it, or close it to send it away.

:heart: Your friend [Staticman](https://staticman.net) :muscle:

---
| Field        | Content                                                                                                                                                                                                                                                                 |
| ------------ | ----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- |
| status       | searching                                                                                                                                                                                                                                                               |
| date_posted  | 2017-02-14                                                                                                                                                                                                                                                              |
| layout       | jobs                                                                                                                                                                                                                                                                    |
| organization | OrgManager                                                                                                                                                                                                                                                              |
| org_url      | https://github.com/m1guelpf/orgmanager                                                                                                                                                                                                                                  |
| title        | Frontend redesign for Orgmanager                                                                                                                                                                                                                                        |
| role         | Frontend Engineer                                                                                                                                                                                                                                                       |
| compensation | gratis                                                                                                                                                                                                                                                                  |
| description  | Orgmanager is an open-source platform where users can generate invites for github organizations.
The website design in very bad rigth now (basic bootstrap) and that'd need to improve...                                                                              |
| skills       | one or more modified views (all would be awesome!).
You can find current views at https://github.com/m1guelpf/orgmanager/tree/master/resources/views                                                                                                                   |
| how_to_apply | Open an issue on the Orgmanager repo:
https://github.com/m1guelpf/orgmanager/
You can also ask for help if you are having problems.,Repo:
https://github.com/m1guelpf/orgmanager
Current views:
https://github.com/m1guelpf/orgmanager/tree/master/resources/views |
| tags         | frontend, design, website, views, bootstrap, laravel                                                                                                                                                                                                                    |
| date         | 2017-02-14T19:46:39.746Z                                                                                                                                                                                                                                                |
| timestamp    | 1487101599                                                                                                                                                                                                                                                              |

### CODE REVIEW

**Comment by simonv3** [comment]
Awesome, thanks @m1guelpf!

**Comment by elioqoshi** [comment]
@m1guelpf is there branding needed here? Maybe I can help

**Comment by m1guelpf** [comment]
@elioqoshi No,what I need is a frontend redesign (If you check curent one at https://orgmanager.miguelpiedrafita.com wou'll know what I mean... the website design is horrible).

**Comment by elioqoshi** [comment]
Well, the branding is not great either, hence asking :)
Okay then

**Comment by m1guelpf** [comment]
@elioqoshi I know, and it would be cool if you could do it...
I just said that I think the website redesign is more important rigth now.

**Comment by elioqoshi** [comment]
Sure, I can work with someone else who can do the frontend I guess

**Comment by m1guelpf** [comment]
@elioqoshi If you still want to help, I've retinked it and OrgManager really needs to be rebranded...

**Comment by elioqoshi** [comment]
I can give it a go :)

**Pull request merged**
