### PR TITLE
New Job - UX/UI for a Open Source project for more transparency in the political process

### PR DESCRIPTION
**Pull request by staticmanapp**
Dear human,

Here's a new entry for your approval. :tada:

Merge the pull request to accept it, or close it to send it away.

:heart: Your friend [Staticman](https://staticman.net) :muscle:

---
| Field        | Content                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      |
| ------------ | -------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- |
| status       | searching                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    |
| date_posted  | 2019-01-06                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   |
| layout       | jobs                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         |
| organization | Open Source project for more transparency in the political process                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           |
| org_url      | http://aboutpolitics.co/Test/mockupindex.html https://gitlab.com/JonasJustus/Politikerklaerer                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               |
| title        | UX/UI for a Open Source project for more transparency in the political process                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               |
| role         | Web design, Usability design                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 |
| compensation | gratis                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       |
| description  | In times of worryingly rising populismus it is our goal to make the process from an election promise to an adopted law transparent and easy to understand. And with your support, the platform’s design will further enhance understanding of our audience. 
The information provided on the platform is partially automatically generate, partially entered manually by users (as in Wikipedia).
First prototype exists, as well as first design ideas.
Who we are:
2 developers
1 lawyer/marketing
1 developer/marketing/project management

Tools we’ve been using so far:
Figma and GoogleDocs

What we offer:
- An exciting open source project giving you the chance to get engaged in helping our democratic systems survive as well as a perfect reference in design
- You won’t be alone and exchange regularly with the project manager. On top, you’ll receive regular feedback from a senior designer, if you wish. |
| deliverables |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              |
| how_to_apply | fs@aboutpolitics.co,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         |
| tags         | UX,UI                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        |
| date         | 2019-01-06T09:47:57.847Z                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     |

### CODE REVIEW

**Comment by belenbarrospena** [comment]
This sounds like an interesting project, but there is no public repository that I can find. Maybe they should clarify in what sense they are "open source".

**Comment by ei8fdb** [comment]
I've emailed the contact address(today) listed above asking for more info.

I'd give it til after FOSDEM to hear back, otherwise I'd close it.

> Hi there,
> 
> You recently posted a job on the jobs board.
> 
> https://github.com/opensourcedesign/jobs/pull/370
> 
> The job sounds interesting and we'd like to post it however before we
> can do that, we need to know if this work will be licensed as open source?
> 
> Do you have a public repository with an open source license?
> 
> If you're not sure, we'd be happy to chat with you about whats involved
> in making it open source.
> 
> Best wishes,
> bernard

**Comment by ei8fdb** [comment]
I got a response from Florian giving me the URL of the public repo. I've added it to the OP above.

Here's his email:

> Hi Bernard,
> nice to hear from you,
> 
> we have a  open source repository:
> https://gitlab.com/JonasJustus/Politikerklaerer
> See the different branches for the status of front and backend. I think we are pretty close to release version 1
> 
> Do you need anythning else?
> 

Based on this I think we should post it.

@belenbarrospena @RDIL thoughts?

**Comment by RDIL** [comment]
At first glance it seems to just be a license and README in that repo.

**Comment by RDIL** [comment]
@belenbarrospena please re-review

**Pull request merged**
