### PR TITLE
New Job - Redesign our app

### PR DESCRIPTION
**Pull request by staticmanapp**
Dear human,

Here's a new entry for your approval. :tada:

Merge the pull request to accept it, or close it to send it away.

:heart: Your friend [Staticman](https://staticman.net) :muscle:

---
| Field        | Content                                                                                                                                                                |
| ------------ | ---------------------------------------------------------------------------------------------------------------------------------------------------------------------- |
| status       | searching                                                                                                                                                              |
| date_posted  | 2017-10-22                                                                                                                                                             |
| layout       | jobs                                                                                                                                                                   |
| organization | Lyfster                                                                                                                                                                |
| org_url      | https://play.google.com/store/apps/details?id=com.life.journal.lyfster&hl=en                                                                                           |
| title        | Redesign our app                                                                                                                                                       |
| role         | Android app design, Logo design                                                                                                                                        |
| compensation | gratis                                                                                                                                                                 |
| description  | We need to redesign our android app Lyfster. A new logo is also needed. 
Link to project https://play.google.com/store/apps/details?id=com.life.journal.lyfster&hl=en |
| deliverables | Logo, Design PSD/PNG, icons svg/png, UX                                                                                                                                |
| how_to_apply | Lyfster<hello@lyfster.com>,https://play.google.com/store/apps/details?id=com.life.journal.lyfster&hl=en                                                                |
| tags         | logo, branding, android, mobile, app                                                                                                                                   |
| date         | 2017-10-22T13:57:31.548Z                                                                                                                                               |

### CODE REVIEW

**Comment by m1guelpf** [comment]
Is this OSS?

**Comment by ei8fdb** [comment]
I don't see any mention of open sourceness anywhere on their site, or on the Google Playstore listing.

I'd say reject.

**Comment by m1guelpf** [comment]
Rejected

**Comment by ei8fdb** [comment]
@m1guelpf heh that was quick.

**Comment by simonv3** [comment]
lol this is kind of ridiculous.

**Pull request closed without merging**
