### PR TITLE
New Job - Create an illustration for 404 - Not found page

### PR DESCRIPTION
**Pull request by staticmanapp**
Dear human,

Here's a new entry for your approval. :tada:

Merge the pull request to accept it, or close it to send it away.

:heart: Your friend [Staticman](https://staticman.net) :muscle:

---
| Field        | Content                                                                                                                                                                                                                                                                |
| ------------ | ---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- |
| status       | searching                                                                                                                                                                                                                                                              |
| date_posted  | 2018-08-01                                                                                                                                                                                                                                                             |
| layout       | jobs                                                                                                                                                                                                                                                                   |
| organization | Vali Admin                                                                                                                                                                                                                                                             |
| org_url      | https://pratikborsadiya.in/vali-admin/                                                                                                                                                                                                                                 |
| title        | Create an illustration for 404 - Not found page                                                                                                                                                                                                                        |
| role         | Illustration Design                                                                                                                                                                                                                                                    |
| compensation | gratis                                                                                                                                                                                                                                                                 |
| description  | Vali Admin is a free and open source dashboard theme.

Create an illustration graphic for 404 error page. Link https://pratikborsadiya.in/vali-admin/page-error.html . At present there is only text, I want a related illustration which can be placed on the page. |
| deliverables | A vector illustration file in either .ai or .svg format.                                                                                                                                                                                                               |
| how_to_apply | Pratik Borsadiya <pratikborsadiya@gmail.com>,Here are some of the sample links of 404 illustrations.
https://github.com/zxcvbg
https://sailsjs.com/asd                                                                                                               |
| tags         | graphic design                                                                                                                                                                                                                                                         |
| date         | 2018-08-01T05:45:11.858Z                                                                                                                                                                                                                                               |

### CODE REVIEW

**Comment by ei8fdb** [comment]
The link to the repo seems wrong. If you follow the org_url link, it has a link to this GH repo: https://github.com/pratikborsadiya/vali-admin

The license there says its MIT.

Maybe @pratikborsadiya can confirm that?

**Comment by elioqoshi** [comment]
Looks good to me. Although I'd recommend SVG files not AI files :)

**Comment by pratikborsadiya** [comment]
Hi @m1guelpf ,

If by OSS you mean if the theme is open source then yes it is. If you mean something else by OSS, Do let me know.

@ei8fdb As mentioned in the description this project is a dashboard theme and the link points to the demo page which is hosted on GitHub pages from this repo. https://github.com/pratikborsadiya/vali-admin/

**Comment by ei8fdb** [comment]
@pratikborsadiya yup, the first thing I followed was the GH repo link and found it was 404. Maybe remove that link? Or you could add the correct GH link.

Apart from that it looks good to me.

**Comment by pratikborsadiya** [comment]
@ei8fdb For me both the repository link (https://github.com/pratikborsadiya/vali-admin) and demo link (https://pratikborsadiya.in/vali-admin/) are working fine. Will you tell me which link is not working for you?

**Comment by ei8fdb** [comment]
In the PR above, the Github repo is listed as:

https://github.com/zxcvbg

Maybe a typo?

**Comment by pratikborsadiya** [comment]
It's not typo. It's intentional. The URL will open a 404 page on GitHub which can be used as an example to create an illustration for 404 page. As the job is to create an illustration for 404 page I intentionally mentioned URLs that will open a 404 not found page.

**Comment by ei8fdb** [comment]
Ah! The formatting of the Staticman PR didn't make that clear. Gotcha.

**Pull request merged**
