### PR TITLE
Update and rename jobs/YYY-MM-DD-ChooseAJobTitle.md to 2016-04-02-log…

### PR DESCRIPTION
**Pull request by sogko**
…o-for-graphql-go

### CODE REVIEW

**Comment by simonv3** [comment]
Looks great except for one thing. Can you make sure the file extension of the file is .md?

That way jekyll won't throw a fit :)

Thanks for submitting the job!

**Comment by sogko** [comment]
Oops, I screwed that one up lol
Also, I moved it to the `jobs` folder where I believe it should be

Cheers!

**Comment by simonv3** [comment]
@sogko great! Merging now :)

**Comment by sogko** [comment]
Awesome! Glad that I bumped into you guys at FOSSASIA 2016!

Cheers!

**Comment by simonv3** [comment]
:D

**Pull request merged**
