### PR TITLE
2015-03-20-internet-of-things-dashboard.md

### PR DESCRIPTION
**Pull request by j8**

### CODE REVIEW

**Comment by simonv3** [comment]
This looks super neat.

**Comment by j8** [comment]
:) just noticed that there is no contact info on the live ad ( http://opensourcedesign.net/jobs/jobs/YYY-MM-DD-ChooseAJobTitle ) and I'm just curious how people will be able to get touch if interested?

**Comment by bnvk** [comment]
Hrm, am I the only one seeing that the URL [http://opensourcedesign.net/jobs/jobs/YYY-MM-DD-ChooseAJobTitle](http://opensourcedesign.net/jobs/jobs/YYY-MM-DD-ChooseAJobTitle) is just the template path? The name of the pull-req mentioned `2015-03-20-internet-of-things-dashboard.md` which does not seem to exist.

**Comment by j8** [comment]
@bnvk your're right. I suppose it's because I used '/' in the title -  "IoT dashboard/ iotstack.io"

**Comment by simonv3** [comment]
Hmm, maybe, though I think it's possibly because the name wasn't updated in the PR (this is at the top of the PR form, rather than at the bottom). This has now happened a couple of times, I'm wondering what we can do to make this clearer. 

I didn't catch it because I confused the name of the PR with the name of the file myself.

**Comment by elioqoshi** [comment]
Not sure if this is the right place, but here is my proposal :)

**Comment by elioqoshi** [comment]
No comments? @j8

**Comment by simonv3** [comment]
My 2¢ is that I'm not sure the cloud also needs the signal sign. Would it also make sense to bring the IoT and the Dashboard a bit closer together? And maybe the grey of dashboard can be a bit lighter?

**Comment by bnvk** [comment]
@elioqoshi maybe try horizontally flipping the cloud, might interplay better... yah, perhaps 10% lighter shade of gray for "Dashboard" as well?

**Comment by elioqoshi** [comment]
No followup on this from the creator, I tend to release my unused logos to the public domain in that case. Thanks anyway!

**Pull request merged**
