### PR TITLE
fix: greetings and stale actions

### PR DESCRIPTION
**Pull request by Ayush7614**
## Description

This PR contains

* Adds a GHA workflow to welcome new users in the project
* If PR is merged then it gives congratulations message to every participants
* Adds a GHA workflow stale.yml for activity of issues and PR

### CODE REVIEW

**Comment by ei8fdb** [comment]
Hi @Ayush7614 can you explain the purpose of this PR?

The workflow for posting a job to opensourcedesign.net is
**For the job poster**
- visit opensourcedesign.net/jobs
- click on `post a job` button, which brings them to https://opensourcedesign.net/jobs/job-form/
- complete the form
- then wait

**For OpenSourceDesign team**
- review the PR created by the job form
- the merge it if its relevant (or don't if not)
- if merged the job goes live to the website
  - if not, it doesn't

Maybe I'm missing understanding - but can you explain where these changes fit in that process?

Is it possible for you to post some screenshots/short movie of this in action?

**Comment by Erioldoesdesign** [comment]
> @Ayush7614 

Please respond to the comments above otherwise we'll look to close this PR :)

**Comment by SethFalco** [comment]
I doubt this really had a purpose tbh.
Given the time, and checking his profile, just Hacktoberfest spam.

In this case, it's not to say that's a bad thing, up to you if this change has value… but:
* https://github.com/pulkit-30/React-Blogging/pull/3
* https://github.com/Elixir-ABESEC/website/pull/7
* https://github.com/actions/setup-dotnet/pull/239
* https://github.com/CodeFlowOrg/forestTreesTagging/pull/92
* https://github.com/nasa/scrub/pull/24
* https://github.com/opensourcedesign/jobs/pull/736

I think adding these actions was just their way of getting the 4 pull requests for Hacktoberfest.

**Comment by Erioldoesdesign** [comment]
> I doubt this really had a purpose tbh. Given the time, and checking his profile, just Hacktoberfest spam.
> 
> In this case, it's not to say that's a bad thing, up to you if this change has value… but:
> 
> * [ CI:fix github actions greetings for new users pulkit-30/React-Blogging#3](https://github.com/pulkit-30/React-Blogging/pull/3)
> * [fix: greetings.yml actions for new users Elixir-ABESEC/website#7](https://github.com/Elixir-ABESEC/website/pull/7)
> * [Added Greeting Actions actions/setup-dotnet#239](https://github.com/actions/setup-dotnet/pull/239)
> * [Added Github Actions Greetings and Stale CodeFlowOrg/forestTreesTagging#92](https://github.com/CodeFlowOrg/forestTreesTagging/pull/92)
> * [Added Github Actions for new users and stale nasa/scrub#24](https://github.com/nasa/scrub/pull/24)
> * [fix: greetings and stale actions #736](https://github.com/opensourcedesign/jobs/pull/736)
> 
> I think adding these actions was just their way of getting the 4 pull requests for Hacktoberfest, that's all.

Worth closing without merging then?

**Pull request closed without merging**
