### PR TITLE
New Job - Material design including logo and assets

### PR DESCRIPTION
**Pull request by staticmanapp**
Dear human,

Here's a new entry for your approval. :tada:

Merge the pull request to accept it, or close it to send it away.

:heart: Your friend [Staticman](https://staticman.net) :muscle:

---
| Field        | Content                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         |
| ------------ | ----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- |
| status       | searching                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       |
| date_posted  | 2019-01-21                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      |
| layout       | jobs                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            |
| organization | Blood Donation                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  |
| org_url      | https://blooddonation.app                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       |
| title        | Material design including logo and assets                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       |
| role         | Web design, Logo design and branding                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            |
| compensation | gratis                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          |
| description  | The project is to convert the blood donation flow to push based, where the donors register in our app and set a base location. If any request posted near them for blood or platelets, they will get a push notification to which they can respond. 
This is open source, free forever, ad-free, no revenue expected project.
I am the only person working on it now. Using Angular, Angular material, and Firebase.
Need logo, assets, UX design using material standards for this PWA. This is responsive and should scale to all devices. |
| deliverables | A logo
UX design and assets for various screens
- Onboarding flow
- Home/Dashboard
- User profile
- List of requests
- Individual request
- About/Contact                                                                                                                                                                                                                                                                                                                                                                                |
| how_to_apply | sriram.s@outlook.in,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            |
| tags         | logo, branding, material design, angular material                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               |
| date         | 2019-01-21T05:22:56.306Z                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        |

### CODE REVIEW

**Comment by forssri** [comment]
The public repo of this app is here, https://github.com/forssri/blooddonation

**Comment by eupiteco** [comment]
I can't quite see the connection with F/LOSS. Is it an app that can be used by blood donation centers or is it for a specific place? Also missing license information

**Comment by forssri** [comment]
@eupiteco thanks for looking into this. Yes it is a Progressive web application being developed to work on all devices and could be used by blood donation centers to organize donation camps and maintain a list of volunteers as well. But more importantly for countries like India where the patients are expected to find a replacement donors, this will be extremely useful. This would be used directly by the patients to post their request and the donors to respond. 

Right now the flow is just the opposite. The patient gets a list of donors numbers and manually have to call them one by one and figure who can donate. 
I am one of the victims who lost the one and only person I ever had, my wife due to this. I wish I could only be useful to the world by doing this.
I would add the license information within 24 hours. Since I am the only person who is working on it, I should admit I am still trying to put together a lot of things. Any help from your side would be great.

**Comment by eupiteco** [comment]
@forssri Thats nice, such a beautiful and strong idea! Try investing your time into gettingr your project more clear to newcomers. As it is right now, there is too little one can figure out about it. 
You can use the `README.md` and [GitHub Pages](https://github.io) to do so. [This guide](https://opensource.guide/) about going open source can also help a lot with getting other people involved.
I send light and strenght to you in your path and wish you the best.
I don't have permisions to accept your merge request but shurely someone will do it asap

**Comment by elioqoshi** [comment]
@forssri I think @ergish and I could help with a logo at least :)

**Comment by forssri** [comment]
@elioqoshi and @ergish, that would be fantastic. I have registered as 'sriram' in the forums and we could continue the discussion in the forum.

**Pull request merged**
