### PR TITLE
Updates Zamphyr job description with more details

### PR DESCRIPTION
**Pull request by marxo**

### CODE REVIEW

**Comment by simonv3** [comment]
Thanks @marxo!

**Comment by ei8fdb** [comment]
@marxo The detail you've added to the job makes it **much** clearer. Thanks for doing that.

**Comment by simonv3** [comment]
Ah, that might be something breaking in the jekyll build. Let me investigate.

**Comment by simonv3** [comment]
Hmm, I'm having some issues getting the site up locally. Can anyone else have a look? @jancborchardt @elioqoshi @m1guelpf ?

**Comment by marxo** [comment]
@simonv3 I might have made a mistake when changing metadata in my submission. Check that out as I'm not sure how metadata should be formatted, but it might be the error behind this failing.

**Comment by simonv3** [comment]
It's not so much your file as that I can't get the site up running locally at all. Recently got a new computer and the set up for the website has changed. Not sure where to go from here :/

**Comment by ei8fdb** [comment]
@Simon I've loaded it here in London.

**Comment by simonv3** [comment]
@ei8fdb and does this job appear on it?

**Comment by jancborchardt** [comment]
The job doesn’t appear on the site for me. @marxo could you try and set the site up locally and see what the issue is? Maybe it’s this part:
```
role: '''UX'', ''UI'''
```
(Cause of too many apostrophes?)

**Pull request merged**
