### PR TITLE
New Job - Design review of the app

### PR DESCRIPTION
**Pull request by staticmanapp**
Dear human,

Here's a new entry for your approval. :tada:

Merge the pull request to accept it, or close it to send it away.

:heart: Your friend [Staticman](https://staticman.net) :muscle:

---
| Field        | Content                                                                                                                                                                                                                                                                                                                                                                                                                                                     |
| ------------ | ----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- |
| status       | searching                                                                                                                                                                                                                                                                                                                                                                                                                                                   |
| date_posted  | 2019-02-16                                                                                                                                                                                                                                                                                                                                                                                                                                                  |
| layout       | jobs                                                                                                                                                                                                                                                                                                                                                                                                                                                        |
| organization | Altair GraphQL Client                                                                                                                                                                                                                                                                                                                                                                                                                                       |
| org_url      | https://altair.sirmuel.design/                                                                                                                                                                                                                                                                                                                                                                                                                              |
| title        | Design review of the app                                                                                                                                                                                                                                                                                                                                                                                                                                    |
| role         | Web app design                                                                                                                                                                                                                                                                                                                                                                                                                                              |
| compensation | gratis                                                                                                                                                                                                                                                                                                                                                                                                                                                      |
| description  | A beautiful feature-rich GraphQL Client IDE for all platforms. Enables you interact with any GraphQL server you are authorized to access from any platform you are on. Much like Postman for GraphQL, you can easily test and optimize your GraphQL implementations. You also have several features to make your GraphQL development process much easier including subscriptions, query scaffolding, formatting, multiple languages, themes, and many more. |
| deliverables |                                                                                                                                                                                                                                                                                                                                                                                                                                                             |
| how_to_apply | hello@sirmuel.design                                                                                                                                                                                                                                                                                                                                                                                                                            |
| tags         |                                                                                                                                                                                                                                                                                                                                                                                                                                                             |
| date         | 2019-02-16T20:15:43.824Z                                                                                                                                                                                                                                                                                                                                                                                                                                    |

### CODE REVIEW

**Comment by ei8fdb** [comment]
Hi Samuel (@imolorhe),

Firstly thanks for the posting. This looks like an interesting job. :)

One thing, I'm a little confused as to what you're looking for - the role says web design, but then the title says design review?

I'm making a wild guess here, but: is it that you're looking for someone to review the usability of the Altair GraphQL Client?

Any help greatly appreciated!

**Comment by imolorhe** [comment]
Yes, exactly. I pretty much designed the app myself with a little help from designer friends, but as I add new features, it becomes difficult to organise them and properly manage the available space in the app.

**Comment by RDIL** [comment]
grr you beat me

**Comment by jancborchardt** [comment]
:D @RDIL normally you’re so fast tho

**Pull request merged**
