### PR TITLE
Add inkscape Open Symbols job

### PR DESCRIPTION
**Pull request by Xaviju**
Inkscape Open Symbols are open source SVG symbol sets that can be used as Inkscape symbols.
The project has grown recently with many contributions
We want to design a website (and branding) to help other users understand the project, install the symbols and how to contribute.

### CODE REVIEW

**Comment by bnvk** [comment]
Cool project. Thanks for submitting it to our job board :)

**Comment by elioqoshi** [comment]
I can help with the branding here but would need help from someone doing the website

**Comment by Espina2** [comment]
I think I can help with the website.

**Comment by Xaviju** [comment]
Great @elioqoshi and @Espina2 

The full info of the desired outcome: http://opensourcedesign.net/jobs/jobs/2017-01-14-inkscape-open-symbols-ux-ui
We have an open issue in the repo with more info: https://github.com/Xaviju/inkscape-open-symbols/issues/57

@Espina2 The website development will be done by myself, but contributions will be appreciated. Did you mean development or design?

@elioqoshi thanks, that's wonderful! It will be great to have an image for social networks (probably only twitter at the moment) and website and maybe a very basic brand styleguide for the website UX/UI designer. If you have any questions about the project or the job, let me know. :)

**Comment by Espina2** [comment]
I can make the UI/UX design and if need it a bit of frontend but it depends on the time I have and the technology you will use.

**Comment by Xaviju** [comment]
@Espina2 That's great! Don't worry too much about the frontend, I can do the coding and ask you questions when required. Does the design requires some advances by @elioqoshi on the branding, doesn't it?

To both, please feel creative and enjoy it, the only requirement is to ensure that users can easily download the symbols and understand how to install them. Thanks again.

**Comment by Espina2** [comment]
Can you do rough wireframe, so I can see what you think its necessary to have in the page?

**Comment by elioqoshi** [comment]
My proposal here. I incorporated a Thunderbolt as it should allow you to have quick access to a wide library of icons, emphasizing its speed and efficiency. It's inside the circle and cutting outside it to open up the circle (Open Source).

The font I used is Noto Sans, an Open Font by Google which supports over 800 languages. I think it was a great fit here.

Let me know what you think

**Comment by Xaviju** [comment]
@Espina2 not sure how to wireframe it, in the original issue we wrote down the features it should have ordered by importance:

Page Home
- Project presentation/basic info (logo, name and description)
- A list of symbols sets and download link (example image, description and link)
- Latest release download link (release number, link)

Section/Page *Installation*
- What's a symbol set in Inkscape and how to use them. (In the future it could be a screencast but for the moment it should be graphical)
- A basic how to install them on different platforms (See README in repo)

Section/Page *Contributions*
- How to contribute (See README in repo)
- Current Contributors (See AUTHORS in repo)

I think that's all

**Comment by Xaviju** [comment]
@elioqoshi thanks for the proposal!

I'm not very sure about the idea of the Thunderbolt although i like the simplicity and the relationship with open source. When I think of symbol sets, i think of the idea of reuse more than speed and efficiency. Thunderbolt could work, speed and efficiency make sense. So if nothing comes to your mind to represent the idea of reuse (nothing comes to mine), we'll stick to the thunderbolt. :+1: 

Love Noto Sans, great choice! :tada: 

About the color, why did you choose this? Just curious. I was thinking of something quite colorful to contrast with the simplicity of the symbols sets. This color i quite bright, which is great. What about a second color? A more colorful option? What do you think?

**Comment by elioqoshi** [comment]
@Xaviju sorry for the delay here!

I think a Thunderbolt is better than a recycle icon here :D 
Maybe ping pong this among others as well.

I don't have a particular opinion about the color. I can show some variants I suppose

**Comment by elioqoshi** [comment]
Added a bit of Inkscape flavor here :) 
Changed the wordmark to orange because that's the Inkscape accent color

**Comment by ryangorley** [comment]
@elioqoshi I like the visual Inkscape reference. If the lighting isn't resonating some other ideas that could be represented symbolically instead of speed, could include: 
- free (libre)
- open
- shared 
- collaboration
- community
- library
- collection
- downloads
- plugin
- resource
- search
I hope that brainstorm helps.

**Comment by Xaviju** [comment]
Sorry for the late reply!!

**Love the Inkscape reference and the color change. Love the typography too. Looks much better :)**
I agree with @ryangorley that I would focus on the library/collection/symbol/shared reference, but I trust @elioqoshi experience. Don't want a recycle bin. :___)
What do you think @elioqoshi? 

@Espina2 are you still available to help on the design?

**Comment by Espina2** [comment]
Yes of course, Im still following this thread. I will start when we have the logo finished.

**Comment by elioqoshi** [comment]
What do you think of this library approach then?

**Comment by Espina2** [comment]
@elioqoshi 
Visually I prefer the lightening one, conceptually I prefer this one. 

I think the last one need a bit of work on the colour's.

**Comment by Xaviju** [comment]
@elioqoshi Nice! I like the mix between library/collection and Inkscape. That's the concept what I was looking for! :))))

@Espina2 could you explain a bit the color work that could be done? I think you mean the two shades of gray but I guess the isotype could change its color to be adapted. :P
@elioqoshi Would you mind sharing the final logo in SVG so @Espina2 could work on the design (when possible)?

## THANKS FOR THE CONTRIBUTION :)

**Comment by elioqoshi** [comment]
Please elaborate regarding the color. It's easily adaptable as long as we stick with it

**Comment by elioqoshi** [comment]
Will send in the final files today (will tweak the icon a bit :)

**Comment by elioqoshi** [comment]
Sorry for the delay, here we go!

http://cloud.elioqoshi.me/index.php/s/kJzQGAOD6zh8zoH

**Pull request merged**
