### PR TITLE
Update 2024-02-02-senior-ux-researcher.md

### PR DESCRIPTION
**Pull request by Erioldoesdesign**
Changes as per this comment https://github.com/opensourcedesign/jobs/pull/873#issuecomment-1923463423

by the original poster @matthiasdebaat

### CODE REVIEW

**Comment by Erioldoesdesign** [comment]
@matthiasdebaat please check over changes

**Review by Arhell — APPROVED** [review]

**Comment by Erioldoesdesign** [comment]
> > @matthiasdebaat please check over changes
> 
> Thanks! I've made some comments

cool! I've tagged our other reviewer to review this when they get a chance but they are busy today so it may be tomorrow/EOW :)

**Review by SaptakS — APPROVED** [review]

**Comment by Erioldoesdesign** [comment]
> Sorry to bother again. The job isn't listed on opensourcedesign.net/jobs/

https://github.com/opensourcedesign/jobs/blob/master/jobs/2024-02-02-senior-ux-researcher.md

Looks like the job has formatting errors from the edits. I'll see if I can fix.

**Comment by Erioldoesdesign** [comment]
https://github.com/opensourcedesign/jobs/pull/876

**Pull request merged**
