### PR TITLE
New Job - Design logo for our tool

### PR DESCRIPTION
**Pull request by staticmanapp**
Dear human,

Here's a new entry for your approval. :tada:

Merge the pull request to accept it, or close it to send it away.

:heart: Your friend [Staticman](https://staticman.net) :muscle:

---
| Field        | Content                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                |
| ------------ | -------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- |
| status       | searching                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              |
| date_posted  | 2018-04-25                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             |
| layout       | jobs                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   |
| organization | Enough                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 |
| org_url      | http://enough.media/                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   |
| title        | Design logo for our tool                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               |
| role         | Logo desing & branding                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 |
| compensation | gratis                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 |
| description  | “Enough” is an innovative tool for journalists to communicate with their sources via encrypted technology. It has a dual mode function, which allows for communication and data transfer on two different levels of security.

On the simpler level, it provides an easy-to-use online platform for journalists to store and receive documents on a day-to-day basis. This function is comparatively easy to install, maintain and use, and significantly resembles more commonly used file-sharing systems such as Dropbox and GoogleDocs. This module not only aims at providing journalists with a practical, standardized tool, but also contributing to a change in culture towards improved protection when storing data.

On a more complex level in cases where a much higher level of security is required, journalists can activate a second layer of the tool. Based on the open source communication software SecureDrop, the use of this element is foreseen in cases where a very high level of security is required due to the nature of the information that is being provided by the source.

The name of the tool alludes to its dual function:
a)	It refers to the fact that in most cases, journalists and their sources do not need to rely on highly complex technical solutions to communicate safely, and that simple measures of encryption are “enough” to provide the necessary security.
b)	It refers to whistleblowers having “enough” of the wrongdoing they are facing, and deciding to report to journalists, while being able to rely on safe communication channels.

We are thus looking for a logo that illustrates the product, and ideally its dual function. Since we are mainly trying to appeal to mainstream journalists, the design should be smooth and simple, rather than complex. Preferred color schemes sunny yellow/white. |
| deliverables | A logo & a set of icons                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                |
| how_to_apply | Veronika (volunteer) veronika.nad@gmail.com,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           |
| tags         | logo, graphic design, journalism                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       |
| date         | 2018-04-26T06:18:45.035Z                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               |

### CODE REVIEW

**Comment by ei8fdb** [comment]
It's a verrry new project and I'm talking to the job poster about it.

**Comment by dachary** [comment]
@m1guelpf @ei8fdb this is a not-yet-formalized project and it may very well be the case that it does not qualify as a valid project for opensourcedesign. I am a big fan of doing things publicly from the very beginning.

In addition to what Veronika posted, the idea was born in the context of SecureDrop and you will find discussions at:

* The forum category [in the SecureDrop Community](https://forum.securedrop.club/t/about-project-enough/646)
* The [discussion that led to the idea for the project](https://forum.securedrop.club/t/securedrop-simplification-take-3/644)

If I was a designer, my question would be: "Yeah, maybe Enough is a nice project. But how do I know it's more than vaporware? I don't want to spend time designing a logo that will never be used!". Honestly I don't have a good answer: it is a gamble :-)

**Comment by m1guelpf** [comment]
@dachary If you can guarantee you're going to OSS the code, then I'm 👍

**Comment by dachary** [comment]
> If you can guarantee you're going to OSS the code, then I'm

I, Loïc Dachary, solemnly swear to only publish my work under a Free Software license. I am also committed to do my very best to enable everyone to [benefit from all the freedom provided by the project under its license](https://www.gnu.org/philosophy/free-software-even-more-important.html).

**Pull request merged**
