### PR TITLE
New Job - Scribus designer for printouts needed

### PR DESCRIPTION
**Pull request by staticmanapp**
Dear human,

Here's a new entry for your approval. :tada:

Merge the pull request to accept it, or close it to send it away.

:heart: Your friend [Staticman](https://staticman.net) :muscle:

---
| Field        | Content                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      |
| ------------ | -------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- |
| status       | searching                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    |
| date_posted  | 2017-05-10                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   |
| layout       | jobs                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         |
| organization | Free Software Foundation Europe                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              |
| org_url      | https://fsfe.org                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             |
| title        | Scribus designer for printouts needed                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        |
| role         | typeset and composition                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      |
| compensation | paid                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         |
| description  | FSFE is a charity that empowers users to use technology and that spreads Free Software.

We are looking for a #FreeSoftware #designer or #layouter, who knows #Scribus and likes to help out @fsfe PR section for some € and a lot of Karma. To get an impression, you can find our material here: https://fsfe.org/contribute/spreadtheword

Your job is to transform our Inkscape defaults into Scribus and layout the Scribus-version for every translation. We pay 40 Euro for each item (= layouting one translation of a leaflet). |
| skills       |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              |
| how_to_apply | Erik eal@fsfe.org,https://fsfe.org/contribute/spreadtheword                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  |
| tags         | fsfe,layout,leaflets,scribus,inkscape,cat content                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            |
| date         | 2017-05-10T14:35:20.614Z                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     |

### CODE REVIEW

**Comment by Xaviju** [comment]
¡It sounds really nice! I was I knew Scribus better. 
I was going to approve this, but not sure if there is any kind of confirmation steps before approval.

**Comment by simonv3** [comment]
Mainly I check for any stray "@"s at the beginning of strings. We should probably do some validation in our form to catch those. In fact, let me create an issue for that... https://github.com/opensourcedesign/opensourcedesign.github.io/issues/119. 

Then it's probably a good idea to check that the org posting it is actually FLOSSy. Since this is FSFE I think it's good to go!

**Comment by simonv3** [comment]
And then usually afterwards I check that it was actually created. If not I pull it down locally and do debugging, which is usually fixing a typo somewhere. 

http://opensourcedesign.net/jobs/jobs/2017-05-10-scribus-designer-for-printouts-needed

**Comment by Xaviju** [comment]
Thanks for the info @simonv3

**Pull request merged**
