### PR TITLE
New Job - Design for an infographic about Free Software

### PR DESCRIPTION
**Pull request by staticmanapp**
Dear human,

Here's a new entry for your approval. :tada:

Merge the pull request to accept it, or close it to send it away.

:heart: Your friend [Staticman](https://staticman.net) :muscle:

---
| Field        | Content                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    |
| ------------ | -------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- |
| status       | searching                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  |
| date_posted  | 2018-07-31                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 |
| layout       | jobs                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       |
| organization | Free Software Infographic                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  |
| org_url      | https://fsfe.org/                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          |
| title        | Design for an infographic about Free Software                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              |
| role         | Infographic Design                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         |
| compensation | paid                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       |
| description  | We are looking for a designer who can create an infographic that visualizes the benefits of Free Software licences based on the imput that we gathered with our campaign group.

The result will be used in a brochure that explains the benefits of Free Software to decision makers in public administration and politics. The brochure is part of the campaign "Public Momney, Public Code!". We want legislation requiring that publicly financed software developed for the public sector be made publicly available under a Free and Open Source Software licence. |
| deliverables | * A infographic that visualizes different arguments (and includes short texts we will deliver)
* The colors used should fit to our campaign publiccode.eu
* We need the results in an open format, so that our volunteer groups in various european countries can adapt the infographic to different languages. We might like to re-use fragments of the infographic in other contexts (leaflets, online, etc.)

For the application:
* Please send us some references
* If you have experince with the design of infographics, this would be perfect                |
| how_to_apply | katharina.nocun@posteo.de,* https://fsfe.org/
* https://publiccode.eu/                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    |
| tags         | graphic design, infographic, brochure, leaflet                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             |
| date         | 2018-07-31T12:03:04.317Z                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   |

### CODE REVIEW

**Comment by ei8fdb** [comment]
jobs_-_design_for_an_infographic_about_free_software

We seem to have these syntax issues often. 

Is it fixable? Not sure where to start...

**Comment by elioqoshi** [comment]
@AnXh3L0 @eupiteco might be able to have a look at the syntax issues?

**Comment by eupiteco** [comment]
It seems that it is trying to mix MD and JS escape sequences but there is misinterpretation when the form is submitted, probably something with the @staticmanapp config.
The `[“katharina.nocun@posteo.de”, “* https://fsfe.org/\r\n* https://publiccode.eu/”]` line is a array with two strings in it: 1 - `“katharina.nocun@posteo.de”` 2 - `“* https://fsfe.org/\r\n* https://publiccode.eu/”`
The second string should be outputted like this, a MD list:
```
* https://fsfe.org/
* https://publiccode.eu/
```
The `\r` and `\n` are escape sequences for carriage return and line feed respectively. What is happening is that the form is wrapped up in JS that is not being iterpreted so the HTML page get a raw JS output as it is, maybe the ideal ouput could be something like

**How to apply:**
katharina.nocun@posteo.de
* https://fsfe.org/
* https://publiccode.eu/
 
I'm still quite a n00b to JS but eventually Il wil take a look at this, maybe the one who coded the jobs section knows where the bug could be.

**Comment by ei8fdb** [comment]
@eupiteco thanks for the explanation. Is there a specific change we can make to fix it in the meantime?

I'm happy to make some PRs to fix it if it helps.

**Comment by eupiteco** [comment]
@ei8fdb Sorry for taking so long, I unsubscribed from this thread. Was wondering what happened to this issue and found no reply on #166 so checked back here...
I think further discussion should be addressed there since this PR is already closed, I'll reply to your question there.

**Pull request merged**
