### PR TITLE
Removing Yocto Project job

### PR DESCRIPTION
**Pull request by belenbarrospena**
We got someone to take care of it.

Signed-off-by: Belen Barros Pena <belen.barros.pena@linux.intel.com>

### CODE REVIEW

**Comment by jancborchardt** [comment]
@bnvk @simonv3 @gillisig @plastelina @belenbarrospena did we want to not remove the accepted jobs, and rather move them to »solved jobs«? Or something similar

**Comment by simonv3** [comment]
I think we were going with "resolved"

**Comment by belenbarrospena** [comment]
Ah, right: sorry. So is it enough if I create a 'resolved' directory and move the file there? Or is there any other magic I need to do?

**Comment by simonv3** [comment]
@belenbarrospena just changing the status object to `resolved` would be enough!

**Comment by simonv3** [comment]
@razetime Instead of closing things, let's make sure the the relevant task gets done first. Not everyone has a lot of time to handle the whole PR system (maybe we need to move away from that, or make it easier somehow?)

**Comment by belenbarrospena** [comment]
Apologies: I should get to this some time next week. Life is a bit mental
at the moment (release coming up).

**Comment by simonv3** [comment]
@belenbarrospena That's cool! There should really be a better system. I'll have to think about it a bit.

**Comment by danielhickman** [comment]
@simonv3 I have a website where it automatically creates PRs based off of inputed data. I could also add email notifications to that too. **But** it doesn't work with GitHub pages.

**Comment by simonv3** [comment]
@danielhickman yeah, for hosting sake that's pretty critical.

**Comment by simonv3** [comment]
And it turns out that GitHub lets you create pages with arbitrary data which I think should replace our process: https://github.com/opensourcedesign/jobs/new/gh-pages/jobs?filename=YYY-MM-DD-ChooseAJobTitle&value=---%0Alayout:%20jobs%0Atitle:%20Job%20Title%0Arole:%20Job%20Role%20%23%20Eg:%20Logo%20Designer,%20UX%20Designer%0Aorganization:%20Organization%20Name%0Agithub:%20github-username%0Acontact:%20email,%20github,%20irc%20channel,%20etc%0Acontributing_md:%20%28optional%29%20%0Acontributors_md:%20%28optional%29%20%0Aurl:%20http://organisation-website.com%0Atags:%20interface%20design,%20branding,%20logo%0Astatus:%20searching%20/%20%0Ahiredrate:%20gratis%20/%20$60%20hour%20/%20$1000%20total%20/%20etc...%0Adate_posted:%20yyyy-mm-dd%0A---%0AWrite%20the%20description%20of%20the%20job%20here.%20Keep%20each%20sentence%20on%20a%20new%20line,%20to%20make%20clean%20diff%20reviews.

**Comment by danielhickman** [comment]
Only for users that are longed in. There's also an issue with using too long of a URL with GitHub. Up like the idea though.

**Comment by danielhickman** [comment]
You guys could iFrame my website run on a VPS server with the code.

**Comment by simonv3** [comment]
@danielhickman If you want to set that up, please do!

**Pull request closed without merging**
