### PR TITLE
New Job - Help design our platform!

### PR DESCRIPTION
**Pull request by staticmanapp**
Dear human,

Here's a new entry for your approval. :tada:

Merge the pull request to accept it, or close it to send it away.

:heart: Your friend [Staticman](https://staticman.net) :muscle:

---
| Field        | Content                                                                                                                                                                                               |
| ------------ | ----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- |
| status       | logged-in                                                                                                                                                                                             |
| date_posted  | 2017-11-07                                                                                                                                                                                            |
| layout       | client                                                                                                                                                                                                |
| organization | Design Mentors Inc.                                                                                                                                                                                   |
| org_url      | http://designmentors.org                                                                                                                                                                              |
| title        | Help design our platform!                                                                                                                                                                             |
| role         | Research and UX/Product Design                                                                                                                                                                        |
| compensation | gratis                                                                                                                                                                                                |
| description  | Design Mentors is a 501(c)(3) international Non-profit. We empower designers and future designers to grow in their careers by connecting them to industry-specific mentoring and education resources. |
| deliverables | Research findings and low-high fidelity mocks.                                                                                                                                                        |
| how_to_apply | David Simpson david@designmentors.org,app.designmentors.org                                                                                                                                           |
| tags         | research, ux, ui, product design                                                                                                                                                                      |
| date         | 2017-11-07T23:34:59.024Z                                                                                                                                                                              |
| category     | clients                                                                                                                                                                                               |
| active       | my-fix                                                                                                                                                                                                |
| permalink    | /clients/kid                                                                                                                                                                                          |

### CODE REVIEW

**Comment by m1guelpf** [comment]
Is this OSS?

**Comment by simonv3** [comment]
I've asked David on the forum.

**Comment by simpson** [comment]
@m1guelpf @simonv3 Hey, we are not an OSS project. We are a non-profit providing a free service to designers.

**Comment by simonv3** [comment]
cc @bnvk @evalica @jancborchardt @victoria-bondarchuk

**Comment by m1guelpf** [comment]
@simonv3 What's the policy for non-profits?

**Comment by simonv3** [comment]
@m1guelpf we don't have one, which is why I ccd some of the others. I'm personally thinking that this should be okay, but we don't really have hard and fast rules for the job board except for "it should be design and open source".

@simpson Like I asked in discourse, but it might make more sense here to keep it all in one place - would you be open to making the site open source?

**Comment by evalica** [comment]
I would prefer to keep our focus and allow only organizations that produce open source software

**Comment by skddc** [comment]
@simpson Stupid question maybe, but if your project is non-profit anyway, then why do you feel the need to lock in that new platform's source code? Wouldn't it make much more sense to have it be open for anyone to improve and contribute to?

**Comment by patdavid** [comment]
> It might be worth amending that language to not include free, since it sounds like that isn't the case.

I think you may have missed that there are [other definitions of the word free outside of "cost"](https://www.gnu.org/philosophy/free-sw.en.html).

**Comment by simonv3** [comment]
@simpson yeah, maybe it's worth qualifying that when we mention free in that sentence we mean free as in libre, not free as in pizza. I concede that this is an obscure tech-y distinction that might not be obvious to people coming from not-flossy background, and as such it's a problem in our design, especially since we're trying to attract those people as well. 

I've added a ticket for just that https://github.com/opensourcedesign/opensourcedesign.github.io/issues/157

**Comment by simonv3** [comment]
@simpson yeah, maybe it's worth qualifying that when we mention free in that sentence we mean free as in libre, not free as in pizza. I concede that this is an obscure tech-y distinction that might not be obvious to people coming from not-flossy background, and as such it's a problem in our design, especially since we're trying to attract those people as well. 

I've added a ticket for just that https://github.com/opensourcedesign/opensourcedesign.github.io/issues/157

**Comment by simonv3** [comment]
@simpson yeah, maybe it's worth qualifying that when we mention free in that sentence we mean free as in libre, not free as in pizza. I concede that this is an obscure tech-y distinction that might not be obvious to people coming from not-flossy background, and as such it's a problem in our design, especially since we're trying to attract those people as well. 

I've added a ticket for just that https://github.com/opensourcedesign/opensourcedesign.github.io/issues/157

**Comment by simpson** [comment]
@skddc The problem is when there are people/companies trying to build products that have similar functionality, however, charge for their solution. We believe design education and mentoring should be free, and are investing in that for others. 

@patdavid  A word can have more than one meaning?! Thank you for the enlightenment, I would have never thought that. I don't know how I could have ever perceived a "free project" as a project that is free to the people who use it.

@simonv3 Sad to see such a snobby response as we are a 501(c)(3) non-profit dedicated to helping others. I would have thought your values were similar, but I guess I don't know enough about OSS.

**Comment by simpson** [comment]
@skddc The problem is when there are people/companies trying to build products that have similar functionality, however, charge for their solution. We believe design education and mentoring should be free, and are investing in that for others. 

@patdavid  A word can have more than one meaning?! Thank you for the enlightenment, I would have never thought that. I don't know how I could have ever perceived a "free project" as a project that is free to the people who use it.

@simonv3 Sad to see such a snobby response as we are a 501(c)(3) non-profit dedicated to helping others. I would have thought your values were similar, but I guess I don't know enough about OSS.

**Comment by simpson** [comment]
@skddc The problem is when there are people/companies trying to build products that have similar functionality, however, charge for their solution. We believe design education and mentoring should be free, and are investing in that for others. 

@patdavid  A word can have more than one meaning?! Thank you for the enlightenment, I would have never thought that. I don't know how I could have ever perceived a "free project" as a project that is free to the people who use it.

@simonv3 Sad to see such a snobby response as we are a 501(c)(3) nona-profit dedicated to helping others. I would have thought your values were similar, but I guess I don't know enough about OSS.

**Comment by simonv3** [comment]
@simpson my response wasn't at all intended to be snobby, and I'm sorry it came off that way. I thought that by being pro-active about changing what we need to clarify before accepting a project we could avoid people mis-interpreting what gets put on the job listing. I'm sorry if that's not how that came off.

We're called Open Source Design. Ultimately that means we cater to free/libre open source projects. That doesn't mean that the work you or your org isn't worthy of contributing to, it just means that it doesn't really fit on the Open Source Design jobs board. 

Can I recommend the Idealist job board? https://www.idealist.org/ I've personally used that to find work on volunteer projects in the past.

**Comment by patdavid** [comment]
> A word can have more than one meaning?! Thank you for the enlightenment, I would have never thought that. I don't know how I could have ever perceived a "free project" as a project that is free to the people who use it.

@simpson I am assuming you forgot your sarcasm tag, though I find your response a little off-putting and misplaced.  I can understand mis-interpreting the "Free" in that light as someone from outside the community, but don't think it calls for sarcastic ridicule.

> Sad to see such a snobby response as we are a 501(c)(3) non-profit dedicated to helping others. I would have thought your values were similar, but I guess I don't know enough about OSS.

That you are a 501(c)(3) doesn't necessarily mean you are any "better" than another corporation.  You're still a corporation - you still have employees that you pay, you still buy things, and you are still looking to employ people. In this case you are not electing to make available what you hope to get for free (as in cost) for free (as in freedom).

Is it also sad that someone posting to a board in the hopes of getting free (as in cost) work done failed to actually read or research a little further what FL/OSS actually _is_?

**Comment by skddc** [comment]
> The problem is when there are people/companies trying to build products that have similar functionality, however, charge for their solution. We believe design education and mentoring should be free, and are investing in that for others.

If you don't want another company to use your code, you can license it for example as AGPL, so they would have to publish any code they use it with, including when they host the software on a server. On the other hand, you're preventing the community from investing actual time and code in your project by locking it down. There's exactly zero difference in your cost for producing the platform alone, so even if there aren't any contributors, the risk you're hinting at is losing an edge over your competitors.

So the real question is, if the code is actually what differentiates your platform. I don't see how it can be immensely novel and innovative from a technological perspective. And it certainly seems to me like your community is much more important to the success of it.

**Comment by simpson** [comment]
@patdavid After receiving multiple emails from a thread I commented on in the forums, I decided to post it as a job. Don't worry, I've contacted the three members and let them know that the values of this community expressly prohibit helping others, especially charities in need. 

@skddc I don't have anything against OSS, I think it is really valuable and important to have, just not right for us. We have a panel of Board Members across the US including Silicon Valley and after we looked at all the options we decided it was in our best interest to build our own platform. We have people who volunteer to help us design and build said platform, all gratis. Despite the ludicrous comments by Pat, we are a non-profit charity that grows as our volunteers help. We use the miniscule donations we receive to cover an accountant, and other minimal necessities to stay in good standing with the IRS. If anything it costs us money out of our pockets, shame on us for wanting to mentor and educate others to help people get jobs. 

@simonv3 I now understand why so many are apprehensive to support OSS or OSD, I know I never will as this is beyond absurd. Please delete all existence of my account in your systems.

**Comment by skddc** [comment]
> we decided it was in our best interest to build our own platform

I understand, but that doesn't conflict in any way with developing it in the open and potentially have others help you build it for free (e.g. with the very job you posted here). Just trying to figure out what's preventing you from doing that, and based on the conversation so far, I still can't identify a real drawback. Pointing to Silicon Valley advice, without explaining the advisor's reasoning, is not very enlightening. But hey, it's your project, and I'm not trying to change your mind per se. Just wanted to point out that making it open-source wouldn't conflict with any of the things you said so far, and probably be rather beneficial even.

By the way, I think you might have mixed up the other two names in your last reply. But also, " this community expressly prohibit helping others, especially charities in need" is not something I would claim about a community, which has been doing literally nothing but that for *years* now, with a lot of productive results.

**Comment by patdavid** [comment]
> the values of this community expressly prohibit helping others, especially charities in need.

@simpson Nobody said this.  This is just sour grapes on your part.  It's entirely up to you to be petulant, but the facts don't support this notion.  Sorry for the misunderstanding about "Free", hopefully it can get amended to clarify to avoid future misunderstandings.

**Comment by simonv3** [comment]
I'm closing this PR because whether or not there is an intention to Design Mentors Inc. an open source product is not up to us, and it sounds like we won't sway their decision either way. There's actionable stuff to try and prevent these misunderstandings in the future: opensourcedesign/opensourcedesign.github.io#157

**Comment by jancborchardt** [comment]
Even though it’s obviously a bit late, I’d like to remind everyone that we have a [Code of Conduct](http://opensourcedesign.net/code-of-conduct/), which among other places is also prominently linked above the job board submission form.

@simpson we are specifically focused on free & open source communities. Yes the »free« can be misunderstood, which is also a reason why we are mainly called **Open Source** Design. The job board is intended to help projects which produce software, websites, etc. which are openly licensed so everyone can use them and contribute. This is to ensure that even if a project fades away, others can continue using it and the effort is not wasted. This part of a comment of yours above is a good example:

> Unfortunately, there were no open source projects that supported what we want our platform to do, and we've had to start building our own to meet the needs that we hear from our users.

– it’s unfortunate, because expecting an open source project to be there, not finding one, and then building the new project in a closed fashion is going to perpetuate that very problem.


--

> Don't worry, I've contacted the three members and let them know that the values of this community expressly prohibit helping others, especially charities in need.

Passive-aggressive comments like this really have no place in any discusson. Yes you are a registered charity, but we are focused on open source projects which is clearly stated all across the site. And that doesn’t put you in a position to discredit the work of this community which is _entirely_ made up of volunteers.

**Comment by pdurbin** [comment]
Wow, lots of unfortunate miscommunication and misunderstanding here. I think we can do better as people. I'm the one who brought Open Source Design to David's attention so please allow me to explain my perspective. A timeline seems best.

- Spring 2013: Phil and David meet at a GitHub Drinkup in Boston. Nice chat. Years go by.
- Oct 29: Phil notices a tweet by David mentioning his new non-profit called Design Mentors and sends him a Twitter direct message, asking if he has heard of Open Source Design. Nope, it's new to him. Seems like a good group. Phil assures him it is.
- Nov 5: Phil suggests a thread that seems on-topic enough to mention Design Mentors and David leaves a note about the new non-profit: https://discourse.opensourcedesign.net/t/convincing-designers-to-embrace-os-methods/312/14 . Phil follows up with a quick post explaining that David is a good guy and mentions his brother would probably make a good mentor.
- Nov 6: David DM's Phil asking about the rules for posting a job even though Design Mentors isn't open source. Phil replies with "Hmm. The rules aren't clear. Bad UX. :)"
- Nov 7: David posts a job, making this pull request.
- Nov 8: Big nerd fight. Flame war. Bad behavior. Violations of the code of conduct. David reaches to Phil via Twitter DM saying he's pretty put off by the Open Source Design team. Because he is so new to Open Source Design, everyone's comments here have more or less equal weight in his mind. To him, it's all one big team.
- Nov 10 (this morning): Phil gets enough information out of David to discover and read the comments in this thread and writes this timeline. He notices that an effort is being made to clarify the language around the rules for posting jobs (thank you!).

Look people, I think we can do better than this. Let's be friends. Please don't make me regret simply trying to do a little matchmaking between two organizations that seem to be fairly aligned. Aren't we all trying to do some good in this world? Please go read http://opensourcedesign.net/code-of-conduct/ if it's been a while.

- "Be radically inclusive to existing members and newcomers looking to learn or participate."
- "Be totally respectful of each others abilities, interests, and personal differences."
- "Be exceedingly kind even in moments of disagreement while working towards consensus."
- etc.

Thanks for reading this.

**Comment by skddc** [comment]
Is his being so nice why the comment that started the negative responses has been deleted by him? I think there would have been better ways of telling him that there are other meanings of the word "free", but one slightly snide remark turned his subsequent response to others into a very aggressive one, only going downhill from there. I agree that we can all do better, but you're making it look like everyone went berserk on him for no reason, and continued to do so, which is not at all what happened.

**Comment by simpson** [comment]
@pdurbin  Thanks Phil, appreciate your thoughts on the situation.

@skddc I don't think I deleted anything, however, I requested @simonv3 delete my account so perhaps that was it. My original statements all still hold true, I think OSS and OSD are valuable and quite important for a great many reasons. I also think they aren't for everyone or everything, and a non-profit charity in need is just as deserving of help. That isn't your focus, and with updated language that will be more clear. 

As we build and grow Design Mentors, we are promoting unity and inclusivity to all, and we have full intention of our resource center to be a place of unbiased access to every resource out there a designer might need. That will include OSD/OSS, to encourage and push people to learn more about what you are all about, and hopefully, it resonates and we can help amplify your voice and promote others to join your mission. 

To Phil's point, in a world full of discourse and messy times, as designers, we ought to stick together.

**Comment by elioqoshi** [comment]
@simpson Thanks for the comments. While your concerns are very valid and should foster discussion among us, your tone of voice in the earlier comments wasn't adequate. However, I appreciate you reaching out and going out there which can be pretty stressful in a crowd of people who have been doing this for so long that they expect everyone is on the same page as well. 

I'd be happy to help in that little time I might have left. Although your job posting doesn't make it to our website, individual designers here could still be interested. Let me know how designers can get involved :)

**Comment by jancborchardt** [comment]
Thanks a lot @simpson! Totally agree with @elioqoshi and what you said, we should stick together as we are all designers and all want to foster our collective community in different ways. :)

**Pull request closed without merging**
