### PR TITLE
Resolve FSFE infographic job

### PR DESCRIPTION
**Pull request by jancborchardt**
As you requested via email by Katharina. Please review @evalica @m1guelpf @ei8fdb @AnXh3L0 :)

### CODE REVIEW

**Comment by ei8fdb** [comment]
Yup, fine with me. Do we want to keep it open til we get an answer to the resolved or closed, as in [186 in the org repo](https://github.com/opensourcedesign/opensourcedesign.github.io/issues/186).

**Comment by jancborchardt** [comment]
@ei8fdb I’d say let’s just do it like this to fix the post, and once we have a consensus at https://github.com/opensourcedesign/opensourcedesign.github.io/issues/186 we fix all the others – cause there’s other posts too we can simply fix all in one. :)

**Comment by AnXh3L0** [comment]
I would also go with closed, resolved feels like it is an issue (like programming or sort of).

**Comment by ei8fdb** [comment]
@jancborchardt I've modified the resolved to closed. I think I've actually edited @m1guelpf's commit, instead of making a new one. Apologies if thats the case..I didn't mean to. :/

**Pull request merged**
