### PR TITLE
New Job - Helping in UI/UX design

### PR DESCRIPTION
**Pull request by staticmanapp**
Dear human,

Here's a new entry for your approval. :tada:

Merge the pull request to accept it, or close it to send it away.

:heart: Your friend [Staticman](https://staticman.net) :muscle:

---
| Field        | Content                                                                                                                                                         |
| ------------ | --------------------------------------------------------------------------------------------------------------------------------------------------------------- |
| status       | searching                                                                                                                                                       |
| date_posted  | 2018-02-02                                                                                                                                                      |
| layout       | jobs                                                                                                                                                            |
| organization | Cryptocurrency wallet app                                                                                                                                       |
| org_url      | http://notyet.com                                                                                                                                               |
| title        | Helping in UI/UX design                                                                                                                                         |
| role         | UI/UX design                                                                                                                                                    |
| compensation | gratis                                                                                                                                                          |
| description  | I'm building an Android & IOS open source app for a digital asset (cryptocurrency) and need someone to help me in UI/UX design , every help would appreciated . |
| deliverables |                                                                                                                                                                 |
| how_to_apply | netcat.av@gmail.com,                                                                                                                                            |
| tags         | app,android,ios,design                                                                                                                                          |
| date         | 2018-02-02T12:10:54.070Z                                                                                                                                        |
| commentDate  | 2018-02-02T12:10:54.070Z                                                                                                                                        |

### CODE REVIEW

**Comment by simonv3** [comment]
Any reference to what the work is? I feel like this post should be a whole lot more fleshed out. @m1guelpf what do you think?

**Comment by m1guelpf** [comment]
@simonv3 The website URL is a placeholder, there's no reference to a repository and the only contact method is a gmail direction. 👎 for me.

**Comment by ei8fdb** [comment]
I've emailed Netcat asking them to respond here.

**Comment by N3TC4T** [comment]
Hey guys , 

sorry for bothering you , actually for now I haven't made a github reposirtory for the app , i thought it's better I push it to github after its almost done .

what should I do right now ?

@ei8fdb Thanks man :)

**Comment by jancborchardt** [comment]
@N3TC4T not a problem. :) Simply submit again as soon as you have a bit more info, ideally a repository or basic landing page with info what it is about. That’s important to get people on board. :) Will close it meanwhile.

**Comment by N3TC4T** [comment]
@jancborchardt Thanks , 

The repository is ready :

https://github.com/N3TC4T/artunis-mobile

Also here is a screen cast from app :

https://youtu.be/PgN5vdVFX5U

Should I submit this again ?

**Comment by jancborchardt** [comment]
@N3TC4T cool! :) Right now we're repairing the job board, but you could manually take over this branch and adjust it to open a new pull request. :)

**Pull request closed without merging**
