### PR TITLE
Added `elixir-lang.moscow` to the jobs

### PR DESCRIPTION
**Pull request by sobolevn**

### CODE REVIEW

**Comment by simonv3** [comment]
Awesome! You can see the posting here: http://opensourcedesign.net/jobs/jobs/2016-07-23-ElixirLangMoscow-website-and-identity

**Comment by elioqoshi** [comment]
I (and Ura generally) can take this on if no one else wants to have the privilege :)

I will however be only able to provide the branding, as I have no buffer for the website design and email template, which is quite time consuming. Maybe someone else can take that on?

**Comment by sobolevn** [comment]
Thanks! I really love your design.

Maybe you can share this post across people you know who might be interested?

**Comment by elioqoshi** [comment]
@sobolevn Thanks! And sure :)

**Comment by sobolevn** [comment]
Hey! Any progress yet?

**Comment by elioqoshi** [comment]
I will get back to you within the week :)

**Comment by sobolevn** [comment]
@elioqoshi Just a ping about the progress :)

**Comment by elioqoshi** [comment]
@sobolevn really sorry about the delay. I have the first proposal ready. Let me know what you think :)

**Comment by sobolevn** [comment]
I like the concept! But is it possible to include a symbol of Moscow (5-point star)? Something like this one:
doc6gx9pqeelyfyoygo4vy_800_480

It of course does not have to be red.

**Comment by elioqoshi** [comment]
How about this?

**Comment by sobolevn** [comment]
Thanks. I really appreciate it! 

I have decided to choose the first one. As it seems much cooler to me.
Can you please send all the source files to my email?

We are using self-created design for now (I am glad that I have found `hack.css`), 
here's the website: https://elixir-lang-moscow.herokuapp.com/

You can choose how would you like your gratis done.

**Comment by elioqoshi** [comment]
Email sent :)
A credit to Ura Design would be appreciated (www.ura.design)

**Pull request merged**
