### PR TITLE
Change Discourse embed from http to https

### PR DESCRIPTION
**Pull request by jancborchardt**
Attempt to fix https://github.com/opensourcedesign/opensourcedesign.github.io/issues/176

Please review @AnXh3L0 @evalica @ei8fdb :)

### CODE REVIEW

**Comment by jancborchardt** [comment]
If you manually paste this into the Javascript console when on a jobs page, it does load the comments:
```
  DiscourseEmbed = { discourseUrl: 'https://discourse.opensourcedesign.net/',
                     discourseEmbedUrl: 'https://opensourcedesign.net/jobs/jobs/2017-12-30-hospitalized-patient-management-module-mockups' };

  (function() {
    var d = document.createElement('script'); d.type = 'text/javascript'; d.async = true;
    d.src = DiscourseEmbed.discourseUrl + 'javascripts/embed.js';
    (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(d);
  })();
```

So I think this change from http to https will fix it.

**Comment by AnXh3L0** [comment]
I believe that's all that is needed to make it work; we can merge it and then see if it works

**Comment by jancborchardt** [comment]
This indeed made it work again! :)

Check it out @elioqoshi, this is what it was supposed to look like all along (and also did, before the https switch :)
https://opensourcedesign.net/jobs/jobs/2017-12-30-hospitalized-patient-management-module-mockups

**Comment by elioqoshi** [comment]
Now that's closer to what one would expect! Great job

**Pull request merged**
