### PR TITLE
New Job - Graphic designer with frontend basic skills

### PR DESCRIPTION
**Pull request by staticmanapp**
Dear human,

Here's a new entry for your approval. :tada:

Merge the pull request to accept it, or close it to send it away.

:heart: Your friend [Staticman](https://staticman.net) :muscle:

---
| Field        | Content                                                                                                                                       |
| ------------ | --------------------------------------------------------------------------------------------------------------------------------------------- |
| status       | searching                                                                                                                                     |
| date_posted  |                                                                                                                                               |
| layout       | jobs                                                                                                                                          |
| organization | AngryToken                                                                                                                                    |
| org_url      | https://angrytoken.com                                                                                                                        |
| title        | Graphic designer with frontend basic skills                                                                                                   |
| role         | Web Design, UI/UX, Front end developer                                                                                                        |
| compensation | paid                                                                                                                                          |
| description  | We need a graphic designer with UI/UX in mind and basic experience with frontend development. Means should be familiar with HTML/CSS at least |
| deliverables | Some portfolio or links to check your skills                                                                                                  |
| how_to_apply | info@angrytoken.com,                                                                                                                          |
| tags         | graphic designer, ui/ux, frontend developer                                                                                                   |
| date         | 2018-09-03T14:13:23.307Z                                                                                                                      |

### CODE REVIEW

**Comment by m1guelpf** [comment]
No GitHub link anywhere. 👎 for me. @simonv3 @jancborchardt thoughts?

**Comment by ei8fdb** [comment]
Message below is a cross post to the GH issue and sent to the info@
email address in the PR.

------------

Hi there,

I am a member of the Open Source Design collective.

At the moment we are discussing your job posting for "Graphic designer
with frontend basic skills".

https://github.com/opensourcedesign/jobs/pull/335

We require some evidence that the project or company produces open
source software.

Please post a comment here:

https://github.com/opensourcedesign/jobs/pull/335

with some explanation of how you produce open source software.

A like to your software repoistory, with an open source license is a
good start.

thanks,
Bernard

-- 
----------
Bernard Tyers

**Comment by belenbarrospena** [comment]
submitted just posted the repo on IRC: https://github.com/AngryTokenProject

**Comment by iwkse** [comment]
Also please if it's possible to update the description, writing GIT use is mandatory and must have team experience

**Comment by jancborchardt** [comment]
The repositories at https://github.com/AngryTokenProject are quite inactive, and there is no code link on the website. I’ll close this for now.

**Pull request closed without merging**
