### PR TITLE
mark Tor job as solved

### PR DESCRIPTION
**Pull request by jancborchardt**
cc @ameellio @elioqoshi @bnvk this is solved, right?

### CODE REVIEW

**Comment by evalica** [comment]
@jancborchardt can you also reference a issue where proposals have been made and discussed? Thanks

**Comment by bnvk** [comment]
Yep. Definitely solved!

**Comment by elioqoshi** [comment]
Yep, this is finished successfully :)

**Comment by eppfel** [comment]
Hey @elioqoshi ,

can you add some points to our [success stories presentation](https://pad.epp.cloud/s/BJu1siGIg). We want to mention this, but there is not much to find about it.

**Comment by elioqoshi** [comment]
@eppfel Yeah, I wanted to blog about it properly but time didn't allow me. I will try to come up with one and let you know.

**Comment by jancborchardt** [comment]
@elioqoshi just mention some key points to @eppfel maybe so we have something for the presentation. :) Doesn’t need to be blocked by writing a blog post.

**Comment by elioqoshi** [comment]
[Styleguide 1.2.pdf](https://github.com/opensourcedesign/jobs/files/713801/Styleguide.1.2.pdf)

Well, here is the first version of the styleguide.
We basically agreed on the colors and the standard logo to be used, how sub projects would be branded and what typography we would use. (in a nutshell)

The styleguide speaks for itself :)

**Pull request merged**
