### PR TITLE
New Job - Job offer UI/UX Designer

### PR DESCRIPTION
**Pull request by andreslucena**
Firstly, congratulations on the great initiative 👏🏽 👏🏽 

At the Decidim project, we're looking for a Designer. It's a paid offer. 

Let me know if there's something missing with the markdown. We tried to do it through staticman, and it wasn't possible to submit it through the bot. I checked out locally with jekyll and it compiles correctly. 

The only field that I didn't know how to change is the `_id` field. 

Thanks!

### CODE REVIEW

**Review by Arhell — COMMENTED** [review]
Create a message using the form, it should help with the ID https://opensourcedesign.net/jobs/job-form/

**Comment by andreslucena** [comment]
@Arhell sorry I forgot to mention it: when we fill the form we get this URL: https://osd-staticman.herokuapp.com/v2/entry/opensourcedesign/jobs/master/jobs with a 422 error.

Screenshot of the error

Maybe it's related to my browser: Firefox 123.0.1 (64-bit)

I'm closing this PR as the submissions deadline has passed. Thanks for your help anyhow @Arhell!

**Comment by Erioldoesdesign** [comment]
> @Arhell sorry I forgot to mention it: when we fill the form we get this URL: https://osd-staticman.herokuapp.com/v2/entry/opensourcedesign/jobs/master/jobs with a 422 error.
> 
> Screenshot of the error
> 
> Maybe it's related to my browser: Firefox 123.0.1 (64-bit)
> 
> I'm closing this PR as the submissions deadline has passed. Thanks for your help anyhow @Arhell!

Pinging @SaptakS just so he's had eyes on this error

It's unlikely to happen regularly though as I don't think we'll get many people submitting via markdown and not the webform

**Comment by SaptakS** [comment]
I haven't tested the form with markdowns extensively and don't know how well it is supported. So might be worth testing. 422 is an Unprocessable Content Error, so it would make sense if staticman was unable to process some of the body data.

**Pull request closed without merging**
