### PR TITLE
New Job - Improve Look and Feel of Thunderbird Website

### PR DESCRIPTION
**Pull request by staticmanapp**
Dear human,

Here's a new entry for your approval. :tada:

Merge the pull request to accept it, or close it to send it away.

:heart: Your friend [Staticman](https://staticman.net) :muscle:

---
| Field        | Content                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 |
| ------------ | ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- |
| status       | searching                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               |
| date_posted  | 2018-03-08                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              |
| layout       | post                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    |
| organization | Thunderbird Project                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     |
| org_url      | https://thunderbird.net                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 |
| title        | Improve Look and Feel of Thunderbird Website                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            |
| role         | Web Design                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              |
| compensation | gratis                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  |
| description  | Thunderbird, the desktop Email client used by 26 million users, is working to revamp our website and we're looking for a passionate web designer to help make the website look and feel more modern and improve the experience of using the website for our users.

You can check out our website at [Thunderbird.net](https://thunderbird.net). It is a good website, but could use improvements to draw attention to the points we'd like to (such as donate and download). We are also planning on adding a get involved page and would like a talented person to help guide the design of that page.

We're looking for a talented designer to help us come up with designs that we can then work to implement. Preferably this person would be good with CSS and HTML, but we can help take any work they produce and incorporate it into the website. If you'd like to take a look at the source code of the site you can [find it here](https://github.com/thundernest/thunderbird-website). |
| deliverables |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         |
| how_to_apply | Ryan Sipes (Community Manager) <ryan@thunderbird.net>,https://thunderbird.net
https://github.com/thundernest/thunderbird-website                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       |
| tags         | comment-subscription                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    |
| date         | 2018-03-08T20:44:46.854Z                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                |

### CODE REVIEW

**Comment by elioqoshi** [comment]
@ryanleesipes I am interested in this as well.

**Comment by elioqoshi** [comment]
Here is a first quick mockup:
image

Ignore the text, I was trying to be consistent with the Firefox landing page but still make it Thunderbird-ish

I used a refreshed Thunderbird logo I created when Firefox 58 came out:
image

Context:
https://twitter.com/elioqoshi/status/972064972665753600

**Comment by ryanleesipes** [comment]
This looks amazing. Let's put something together. Email me and we'll jump into a chat. I love this.

**Comment by elioqoshi** [comment]
@ryanleesipes happy you like it! Will reach out soon :)

**Comment by simonv3** [comment]
<3 the thunderbird mockup too @elioqoshi

**Comment by elioqoshi** [comment]
Thanks!

Here is an update 
web 1920 1

**Comment by ryanleesipes** [comment]
@pmarquees didn't see this come through. Feel free to share ideas here, or in the issue: https://github.com/thundernest/thunderbird-website/issues/31

**Pull request merged**
