### PR TITLE
New Job - UX/UI design help needed for a new  file sharing project

### PR DESCRIPTION
**Pull request by staticmanapp**
Dear human,

Here's a new entry for your approval. :tada:

Merge the pull request to accept it, or close it to send it away.

:heart: Your friend [Staticman](https://staticman.net) :muscle:

---
| Field        | Content                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     |
| ------------ | --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- |
| status       | searching                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   |
| date_posted  | 2018-02-06                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  |
| layout       | jobs                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        |
| organization | Arbore                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      |
| org_url      | http://arbo.re                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              |
| title        | UX/UI design help needed for a new  file sharing project                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    |
| role         | Interaction design, User interface design                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   |
| compensation | gratis                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      |
| description  | Arbore is a social file-sharing application. The goal is to provide a way for people to share pictures/documents/whatever with their friends/colleagues/contacts privately and safely. The second goal is to reduce the dependency of people to the silo of data that are Facebook, Google, Dropbox ... that trap them. In short, to provide a viable alternative solution and to help people protect their private life.

Alternative solution already exists but require technical knowledge and time to setup and maintain. In part because of that, they are not very successful. Arbore is my attempt to change that. I think that such a tool should be as easy to setup and use as VLC.

This project is already well underway and close to a working MVP. That said, I need help from people more knowledgeable than me in UX and UI design to make it really slick and beautiful. I'm just a developer after all ! Even if the current state is not terrible, it could be much better. And on a project like this, it's the difference between success or not. |
| deliverables | There is a lot of low hanging fruit that you can help me with:
- UX/UI feedback and suggestion
- UX/UI design of the remaining part of the application
- design/marketing for the website
- UX/UI design for the on-boarding process
- probably some other things                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      |
| how_to_apply | Michael Muré <batolettre@gmail.com>,http://arbo.re - future homepage, currently redirecting to the github repository
https://gitter.im/Arbore/Lobby - Gitter lobby
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       |
| tags         | graphic design, interface, interaction design, UI, UX                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       |
| date         | 2018-02-06T11:43:08.158Z                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    |
| timestamp    | 1517917388                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  |

### CODE REVIEW

**Comment by MichaelMure** [comment]
Huuu, it's all broken on the website :-|
The description is missing and the "how to apply" is badly formatted.

**Comment by elioqoshi** [comment]
I think the way the description is written is a tad arrogant and puts down efforts of other projects like Nextcloud (which is pretty successful by most definitions).  Maybe also offering another alternative for contact rather than gmail after bashing Google would be also more appropriate. 

> And on a project like this, it's the difference between success or not

Indeed. But the request is quite broad and is a lot of work actually. Especially for something without any budget. It's hard to expect people to join by just inviting them to generally fix UX stuff. If you would scope down your work by requesting smaller tasks, I'm sure that would be more interesting for designers.

That is my personal input and does not reflect what OSD stands for though.

**Comment by tessgadwa** [comment]
Personally I would be much more interested in a broad scope interaction
design project such as this one, which contains much more opportunity to
learn, than with narrow task base requests such as designing a logo. They
also offer the designer a greater role and impact in the evening
development of the project. Agree with the other criticisms, but I would
advocate strenuously for leaving broad scope projects as part of the mix,
whether compensated or not.

**Comment by MichaelMure** [comment]
> I think the way the description is written is a tad arrogant and puts down efforts of other projects like Nextcloud (which is pretty successful by most definitions). 

Sorry if that comes out as arrogant, I was just trying to explain the difference between this project and what exist otherwise, and why UI/UX/usability is so important here. Many other projects do a good job but they have a different focus. I just had so much the question "but why do this while XXX exist ?".

> Maybe also offering another alternative for contact rather than gmail after bashing Google would be also more appropriate.

There is the Gitter lobby.

So yes, the scope is broad. I don't expect everything to be covered, but I'm looking for anyone that can help me on these subjects, for a short or a long time.

**Pull request merged**
