### PR TITLE
Add Staticman data

### PR DESCRIPTION
**Pull request by staticmanapp**
Dear human,

Here's a new entry for your approval. :tada:

Merge the pull request to accept it, or close it to send it away.

:heart: Your friend [Staticman](https://staticman.net) :muscle:

---
| Field        | Content                           |
| ------------ | --------------------------------- |
| status       | searching                         |
| date_posted  | 2017-02-22                        |
| layout       | jobs                              |
| organization | Test Value                        |
| org_url      | http://opensourcedesign.net/jobs/ |
| title        | Test Title                        |
| role         | Test Title                        |
| compensation | gratis                            |
| description  | Test Title                        |
| skills       | Test Title                        |
| how_to_apply | Test Title,Test Title             |
| tags         | Test Title                        |
| date         | 2017-02-22T16:42:58.707Z          |

### CODE REVIEW

**Comment by skddc** [comment]
Just a quick question, as these PRs pop up in my notifications all the time, but it's impossible to know what's in them: Would it be possible to include some information about the content in the title?

**Comment by simonv3** [comment]
@skddc looks like the answer is no https://github.com/opensourcedesign/jobs/pull/172, or at least not in what I thought would be an obvious way. 

Logged here: https://github.com/eduardoboucas/staticman/issues/79

**Comment by simonv3** [comment]
@skddc Once staticman deploys their current master to their main API, this should be fixed. 👍

**Comment by skddc** [comment]
w00t, thanks!

**Pull request closed without merging**
