### PR TITLE
Update status for 2019-10-30-help... mailchain theme

### PR DESCRIPTION
**Pull request by tboeckmann**
2019-10-30-help-designing-a-distinguishable-clean-and-modern-looking-logo-and-color-scheme.md

`status` from `searching` >> `closed`

### CODE REVIEW

**Comment by ei8fdb** [comment]
Looks fine to me. 

@tboeckmann - was this job live previously?

**Comment by tboeckmann** [comment]
@ei8fdb it was live, but was published in error (see [here](https://github.com/opensourcedesign/jobs/issues/410#issuecomment-549124574))

**Comment by ei8fdb** [comment]
👍

**Comment by dmichl** [comment]
confirm merge

**Pull request merged**
