### PR TITLE
chuaccheng-UIUXGraphicDesign-fun.md

### PR DESCRIPTION
**Pull request by chuaccheng**
Hello! Just wanted to submit this, hope it's alright :)

Have a lovely day ahead!

### CODE REVIEW

**Comment by simonv3** [comment]
Hey @chuaccheng it looks good but it also looks like you're putting yourself out there to be hired? Is that your intention? If so, then this is probably not the best place for it. 

Maybe a better space for that is: https://github.com/opensourcedesign/organization

**Comment by chuaccheng** [comment]
Hi @simonv3 👋 !
Oh!! Actually, I was just looking to contribute to open source work!! 😄  not necessarily looking to be hired, just want to contribute designs! Should have phrased it more appropriately, my bad!

And so sorry about the PR! Still new to this, but will keep it in mind in future! 😃

**Comment by belenbarrospena** [comment]
@chuaccheng that's awesome that you want to contribute, and well done on sending that pull request. No need to be sorry: it is not necessarily obvious how things should be done, and in any case, one of the points of contributing to open source is that it is a safe place to learn and make mistakes :)

Like @simonv3 said, you should add yourself to the "people" list. The process is pretty much the same (send a pull request), or you can comment on 

https://github.com/opensourcedesign/organization/issues/29

And of course have a look at the list of projects looking for design contributions

http://opensourcedesign.net/jobs/

and see if there is anything there you would like to help with. Ah, and welcome to open source! :)

**Comment by chuaccheng** [comment]
Hello @belenbarrospena 😸 

Thank you so much!!! Yes will definitely learn from this :)

Will add to the "people" list as well!! :) Looking forward to working with you guys on open source!

Have a great week ahead! 😃

**Comment by simonv3** [comment]
@chuaccheng no worries! Fixing the way people add themselves and the job listings are created is definitely on the horizon. Have a look here: https://github.com/opensourcedesign/jobs/issues/91

We could probably use some design thoughts on it too ;)

Welcome! And I'm sorry our process still leaves so much to be desired.

**Pull request merged**
