### PR TITLE
Revert "Delete 2017-07-09-create-a-logo-for-recase-project.md"

### PR DESCRIPTION
**Pull request by evalica**
Reverts opensourcedesign/jobs#234

### CODE REVIEW

**Comment by evalica** [comment]
See my comments about 'status' on https://github.com/opensourcedesign/jobs/pull/234

**Comment by m1guelpf** [comment]
@evalica Normally, people ask for deletion, and keeping it can lead to confusion, so I'd suggest to delete completed jobs.

**Comment by evalica** [comment]
We have the status and in the future we might want to display resolved jobs, see https://github.com/opensourcedesign/opensourcedesign.github.io/issues/83 in order to assess the success and response times.

**Comment by evalica** [comment]
Since we are changing statuses, see https://github.com/opensourcedesign/jobs/pull/242/files/458e9c3900763b23b4791c37349e6813a021fd65..b1364fc3b53e1489e50eac8abf2e4945a6e8ee9e can someone revert the delete?

**Comment by evalica** [comment]
Created a PR for the status change. Thank you

**Pull request merged**
