### PR TITLE
New Job - Mockups Designs for Social platform

### PR DESCRIPTION
**Pull request by staticmanapp**
Dear human,

Here's a new entry for your approval. :tada:

Merge the pull request to accept it, or close it to send it away.

:heart: Your friend [Staticman](https://staticman.net) :muscle:

---
| Field        | Content                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           |
| ------------ | --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- |
| status       | searching                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         |
| date_posted  | 2019-04-08                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        |
| layout       | jobs                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              |
| organization | Codeuino                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          |
| org_url      | http://codeuino.org                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               |
| title        | Mockups Designs for Social platform                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               |
| role         | UI/UX mockups designing                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           |
| compensation | gratis                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            |
| description  | Codeuino which is a volunteer-driven non-profit open source Social networking organisation that provides various robust frameworks solutions which could span the entire world through building all kinds of social environments, discussion portals and collaboration platforms, giving prospectus to various other organisations, users and outreachers to use social media in a custom way. DONUT is a major member project of codeuino which is an open source social networking platform like Facebook which allow individual users and organisations to setup their own social platform along with multi integrated system.

You can find about the project here https://github.com/codeuino/Social-Platform-Donut

We are being run by a large community on slack, here is the link ( www.slack.codeuino.org )

What we need to have is we currently have some Mockups displayed on our github Repo but we have planned to change since we are developing new modules so that would required new UI.

So we need to have a good looking "Feeds Page" what we see in facebook but this page should not be exactly similar to facebook, linkedin feedspage. We need to have a unique layout.
Along with this Dashboard mockup is required. There exist 2 dashboards that is one for community and other for individual users. So new and different design for both. |
| deliverables | Unique design for Feeds page, dashboard, project displayed page, general landing page.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            |
| how_to_apply | Jaskirat Singh (juskirat2000@gmail.com) and community support at support@codeuino.org,https://github.com/codeuino/Social-Platform-Donut                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           |
| tags         | Mockups, UI/UX, Social Platform, Open Source                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      |
| date         | 2019-04-08T12:01:25.571Z                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          |

### CODE REVIEW

**Comment by jaskirat2000** [comment]
It shows that I can't merge

**Comment by jaskirat2000** [comment]
.

**Comment by belenbarrospena** [comment]
@jaskirat2000 no, you can't :) 

We moderate the job requests to make sure they come from free / open source projects. It's done fairly quickly, though: I am sure the job will be reviewed and merged soon.

**Comment by jaskirat2000** [comment]
Thanks looking forward to it.

**Pull request merged**
