### PR TITLE
New Job - New icon for Extension

### PR DESCRIPTION
**Pull request by staticmanapp**
Dear human,

Here's a new entry for your approval. :tada:

Merge the pull request to accept it, or close it to send it away.

:heart: Your friend [Staticman](https://staticman.net) :muscle:

---
| Field        | Content                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              |
| ------------ | ---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- |
| status       | searching                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            |
| date_posted  | 2018-03-20                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           |
| layout       | jobs                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 |
| organization | Notification Sound WebExtension                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      |
| org_url      | https://addons.mozilla.org/en-US/firefox/addon/notification-sound/                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   |
| title        | New icon for Extension                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               |
| role         | Logo design & branding                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               |
| compensation | gratis                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               |
| description  | Notification Sound plays a sound when Firefox shows a notification, since not all notification daemons do that.

I made a very basic icon a few years ago that tried to convey what a "notification sound" is, but it was rather... basic from the beginning.

I'd like to have a much smoother icon and in the process of updating it also have a vector (SVG) version.

I'm very open to what the icon actually contains, but I'd rather stick to something that's not too abstract. The icon is only used as the add-on icon and never exposed in add-on specific GUI (except for the settings page, where Firefox displays it by default). |
| deliverables | - SVG extension icon                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 |
| how_to_apply | Martin Giger, <martin@humanoids.be>,Source code: https://github.com/freaktechnik/notification-sounds
Current icon: https://github.com/freaktechnik/notification-sounds/blob/master/images/icon-64.png                                                                                                                                                                                                                                                                                                                                                                                                                                               |
| tags         | logo, icon, extension, webextension, firefox                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         |
| date         | 2018-03-20T20:31:30.957Z                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             |

### CODE REVIEW

**Comment by elioqoshi** [comment]
@freaktechnik does this work for you? :)

image

**Comment by freaktechnik** [comment]
@elioqoshi yeah, that works for me, thank you for the quick response!

**Comment by elioqoshi** [comment]
[Firefox Notification Sound Icon.zip](https://github.com/opensourcedesign/jobs/files/1831525/Firefox.Notification.Sound.Icon.zip)

@freaktechnik Great! There you go :)

**Comment by freaktechnik** [comment]
@elioqoshi do you want any attribution? I assume you're fine with the SVG being licensed under the MPL-2.0?

**Comment by elioqoshi** [comment]
@freaktechnik no attribution required, I leave that to you :)

**Comment by m1guelpf** [comment]
Should I change the status to closed and merge or close this?

**Comment by jancborchardt** [comment]
@m1guelpf good call! I adjusted it to `solved` and referenced @elioqoshi’s post with the icon, and merged. :)

**Pull request merged**
