### PR TITLE
New Job - Sticker pack artwork

### PR DESCRIPTION
**Pull request by staticmanapp**
Dear human,

Here's a new entry for your approval. :tada:

Merge the pull request to accept it, or close it to send it away.

:heart: Your friend [Staticman](https://staticman.net) :muscle:

---
| Field        | Content                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               |
| ------------ | ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- |
| status       | searching                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             |
| date_posted  | 2018-03-26                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            |
| layout       | jobs                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  |
| organization | Dimension (t2bot.io)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  |
| org_url      | https://github.com/turt2live/matrix-dimension                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         |
| title        | Sticker pack artwork                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  |
| role         | Graphic design                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        |
| compensation | gratis                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                |
| description  | Dimension (an open source integrations manager for clients like Riot.im) is tackling stickers in an upcoming update and needs some stickers to be included in the launch.

Stickers in the context of Dimension or Riot.im are very similar to Telegram stickers in that they are images sent to a room/channel for everyone to see. Dimension would serve the purpose of providing those stickers so that users can easily post them to the room.

The sticker packs being designed should have an overall theme to them, such as "cats" or "science". They do not necessarily need to be tied to emoji, but should have some sort of emotion to be associated with them.

Please see the license of Dimension on Github for information about how these stickers may be used. |
| deliverables | * 10-20 stickers per "pack" (or theme)
* A white outline on each sticker to make it feel more sticker-like
* Different themes for each pack (creative freedom on the themes, please double check before designing though)
* Preferably the source files would be provided, however 512x512 PNGs are also acceptable                                                                                                                                                                                                                                                                                                                                                                                                                                                                |
| how_to_apply | Travis R (lead dev) <@travis:t2l.io on [riot.im](https://about.riot.im)>,Github repo: https://github.com/turt2live/matrix-dimension
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 |
| tags         | graphic design, artwork, stickers                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     |
| date         | 2018-03-26T17:02:14.509Z                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              |

### CODE REVIEW

**Comment by m1guelpf** [comment]
@turt2live Merged!

**Comment by elioqoshi** [comment]
This is a huge undertaking if it's something done from scratch. I wonder if there are any freely licensed stickers packs out there which can be added?

**Comment by turt2live** [comment]
@elioqoshi I'd happily use freely licensed packs out there, but my research is failing me :( If you have any suggestions, please let me know.

**Comment by elioqoshi** [comment]
@turt2live In the past we have done some Illustrations for the Linux Foundation, which can be turned into stickers: https://ura.design/projects/openchain

The designs are CC0. That could be a good start

Also, the Mozilla Lions for l10n might be nice too, although licensed under CC-BY-SA (we transferred copyright to Mozilla when working on this): https://ura.design/projects/mozilla-l10n

I think the penguins could be a nice start.

**Comment by turt2live** [comment]
The penguins do look great! Thanks for pointing them out. Considering they are CC0, that makes things all the better.

I think I'll still keep the posting around in the hopes that someone gets bored/creative and wants to work on a bunch of stickers, or has pointers for more assets that can be used.

**Comment by tessgadwa** [comment]
Adding a way to show credit / link to an artist's website might be a nice
incentive.

**Comment by turt2live** [comment]
@tessgadwa Looks like I didn't mention it, but the author(s) would certainly be credited at least within Dimension.

**Comment by tessgadwa** [comment]
Nifty!

Having a credit link within the app wouldn't be as important to me
personally, but I imagine for some creators it could be a major
consideration.

**Pull request merged**
