### PR TITLE
New Job - Logo & design for a one-page web app

### PR DESCRIPTION
**Pull request by staticmanapp**
Dear human,

Here's a new entry for your approval. :tada:

Merge the pull request to accept it, or close it to send it away.

:heart: Your friend [Staticman](https://staticman.net) :muscle:

---
| Field        | Content                                                                                                                                                                                                    |
| ------------ | ---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- |
| status       | searching                                                                                                                                                                                                  |
| date_posted  | 2018-04-04                                                                                                                                                                                                 |
| layout       | post                                                                                                                                                                                                       |
| organization | CloudCover                                                                                                                                                                                                 |
| org_url      | https://cloudcover.me/                                                                                                                                                                                     |
| title        | Logo & design for a one-page web app                                                                                                                                                                       |
| role         | 'Logo Design', 'Web Design'                                                                                                                                                                                |
| compensation | gratis                                                                                                                                                                                                     |
| description  | We would love a pretty design for https://cloudcover.me it's 100% open source, and while it works now it's not pretty can could need a logo, and a favicon with some minor design for the webpage it self. |
| deliverables | - Logo
- Favicon
- Responsive design for the page, with errors and load indicators.                                                                                                                      |
| how_to_apply | Allan Kimmer Jensen <allankimmerjensen@gmail.com>,- https://cloudcover.me/
- https://github.com/bizarrefishfry/CloudCover                                                                                 |
| tags         | logo, branding, app, website, privacy                                                                                                                                                                      |
| date         | 2018-04-04T13:02:23.497Z                                                                                                                                                                                   |
| timestamp    | 1522846943                                                                                                                                                                                                 |

### CODE REVIEW

**Comment by m1guelpf** [comment]
@bizarrefishfry Merged!

**Comment by elioqoshi** [comment]
@saturate I'd definitely like to help with a logo. Maybe even the landing page design (if someone can implement the HTML)

**Comment by Saturate** [comment]
Hey @elioqoshi that sounds awesome! That would be very welcomed, let me know if you need anything at all.

I can implement the HTML no problem, or even better @bizarrefishfry can do it - as he's learning by doing, and I'm more like the mentor. And don't make it easy on him, animations ect. are fine if you so desire.

You can take a look at https://github.com/bizarrefishfry/CloudCover/issues/6 for the issue on this.

**Comment by Saturate** [comment]
And woops, seems like I broke the @staticmanapp a bit with the formatting.

**Comment by elioqoshi** [comment]
Sounds good! I work for OONI ( https://ooni.torproject.org) so this topic is close to my heart :)

**Comment by bizarrefishfry** [comment]
Yeah man! I am totally up for it :)! 
Lets get this thing going.

**Comment by harshzalavadiya** [comment]
hello guys,
checkout this designs if you like any

cloud-hide logo

color and any other changes can be done let me know if you like anything

and plus i can also help with html as well if needed for any other logo

**Comment by elioqoshi** [comment]
Oh seems this exploded, the more the merrier :)

This is my proposal:

image

The icon should work well on small sizes, including favicons

**Comment by Saturate** [comment]
You guys ROCK, thanks so much for now - @bizarrefishfry will have to provide feedback.
Can't wait till see more :-)

**Comment by bizarrefishfry** [comment]
I really like all of the logos and I prefer logos with text, so we are going to roll with the logo @elioqoshi made :). 

Would anybody be up for making some mock-up designs? I will gladly give creating the HTML a shot :)

**Comment by elioqoshi** [comment]
Cool! @bizarrefishfry I will send you a mockup by tomorrow :)

**Comment by bizarrefishfry** [comment]
Awesome! Looking forward to taking a look :)!

**Comment by elioqoshi** [comment]
Here we go :)

web 1920 1

**Comment by elioqoshi** [comment]
That's a rather quick mockup, I guess you could animate the cloud and also do a different section for the What is domain fronting section. But that's a good start I believe

**Comment by HeikoTietze** [comment]
Quick, but nice and clean, wouldn't animate anything. The crenelations look a bit weird but if big brother is watching you...

**Comment by harshzalavadiya** [comment]
is anyone converting it? otherwise i can code.

**Comment by Saturate** [comment]
@elioqoshi Looks like, but I think that the "Last frontable domains" might require some more features, or attention, as far as I understand it - this is a list that could be important. But I guess @bizarrefishfry can tell us some more.

**Comment by bizarrefishfry** [comment]
I am quite busy currently, so it might take some time to get around to. So if @harshzalavadiya wants to start, feel free! :) 

@Saturate Nope, the last frontable domains only contains that for now. I might add something else later, but for now should be sufficient.

**Comment by Saturate** [comment]
The plan is to use react for the frontend in the near feature, so if you implement it - please have this in mind. You could even implement it in React if you like.

Also we use SCSS as a preprocessor for the CSS.

Otherwise just ask us.

Thanks so much again people!

**Comment by harshzalavadiya** [comment]
@Saturate  sure

**Comment by elioqoshi** [comment]
Folks, here is the logo: https://github.com/uracreative/works/tree/master/CloudCover

**Comment by elioqoshi** [comment]
The page looks solid :) 
I might make the font size smaller (my fault) and Paragraph should be Regular, not Medium :)

**Comment by elioqoshi** [comment]
I'd rather leave the code to the coders :)

**Comment by bizarrefishfry** [comment]
Sorry for my broken English, long day at work, I meant if @harshzalavadiya implements the changes proposed by @elioqoshi, we have a good layout 😄

**Comment by harshzalavadiya** [comment]
@bizarrefishfry, @elioqoshi

thank you for feedback
i'll fix then fonts and spacing problems and change the logo to actual one
then you can review it once if everything is fine then i'll make a PR

**Comment by harshzalavadiya** [comment]
[PR#8](https://github.com/bizarrefishfry/CloudCover/pull/8) has been raised please check it and merge if no issues are there.

**Comment by bizarrefishfry** [comment]
@harshzalavadiya Sorry for taking so long, I am super busy at the moment. 
I hope to get around to it this weekend 😁

**Pull request merged**
