### PR TITLE
Proposed a new job to create a logo for `git-secret`

### PR DESCRIPTION
**Pull request by sobolevn**

### CODE REVIEW

**Comment by Hiyorimi** [comment]
Bad idea, git-secret logo is already awesome.

**Comment by sobolevn** [comment]
Which one?

**Comment by elioqoshi** [comment]
Thanks @sobolevn !

Here is my proposal, let me know what you think :)

**Comment by bnvk** [comment]
Thats awesome you two, I :heart: `git-secret`

**Comment by sobolevn** [comment]
@elioqoshi wow, that's so cool! I really like it.

Could you please send me ([my email](mailto:mail@sobolevn.me)) this logo in high quality with two versions: the whole logo and just the lock part?

I will add it in the next release, and set credits for your awesome work!

**Comment by elioqoshi** [comment]
@sobolevn Happy that you like it! I sent you an email :)

The font used is Lato Black. It's an open font which you can get from here:
https://www.fontsquirrel.com/fonts/lato

**Comment by sobolevn** [comment]
Ummm...

One more thing, I have missed with the file location: https://github.com/opensourcedesign/jobs/blob/gh-pages/2016-06-11-Create-A-Logo-For-git-secret.md

**Comment by elioqoshi** [comment]
@sobolevn What do you mean? Sorry, I'm not good with pushing things via git :)
You have the files via email

**Comment by sobolevn** [comment]
No, I am talking about the job-file location: 


They should be inside the `jobs/` folder.

**Comment by elioqoshi** [comment]
Ah I see! @simonv3 can you help me here please? :D

**Comment by simonv3** [comment]
@elioqoshi, @sobolevn fixed :)

**Pull request merged**
