### PR TITLE
New Job - Design a personal website

### PR DESCRIPTION
**Pull request by staticmanapp**
Dear human,

Here's a new entry for your approval. :tada:

Merge the pull request to accept it, or close it to send it away.

:heart: Your friend [Staticman](https://staticman.net) :muscle:

---
| Field        | Content                                                                                                                                                                            |
| ------------ | ---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- |
| status       | searching                                                                                                                                                                          |
| date_posted  | 2018-07-09                                                                                                                                                                         |
| layout       | jobs                                                                                                                                                                               |
| organization | Personal website                                                                                                                                                                   |
| org_url      | https://github.com/ingridrauany/ingridrauany.github.io                                                                                                                             |
| title        | Design a personal website                                                                                                                                                          |
| role         | web design                                                                                                                                                                         |
| compensation | gratis                                                                                                                                                                             |
| description  | This project is about my personal portfolio, to publicize my skills on Front-End Development (HTML, CSS, JavaScript), jobs and projects. It's like an alternative to a curriculum. |
| deliverables |                                                                                                                                                                                    |
| how_to_apply | Ingrid Rauany <ingrid.rauany@hotmail.com>,Some websites that i liked:
https://docs.google.com/document/d/1z4djziil3wmp_LvX-4OrNIOCe8PFjj8dYY1Xi2mmO30/edit?usp=sharing            |
| tags         | website, portfolio, design                                                                                                                                                         |
| date         | 2018-07-09T18:13:37.604Z                                                                                                                                                           |

### CODE REVIEW

**Comment by belenbarrospena** [comment]
Am I misunderstanding this job request? It sounds to me like a request for designing a personal website. If that's correct, should we be including it in our jobs board for FOSS projects?

**Comment by tessgadwa** [comment]
Could be good for a designer looking to build up there portfolio, I guess.

**Comment by elioqoshi** [comment]
@m1guelpf I think we should review these since it's a big red flag anyway and 2 OSD Members agreeing on merging a PR is usually a good number :)

Having said that, I find it funny someone would ask (gratis) to design their own website to promote their web development skills. In any case, beyond that it might be useful for us to analyze this and whether we don't get the message across the right way what the Job board is about since some people misunderstand it.

**Comment by m1guelpf** [comment]
@belenbarrospena From what I understand, the website would be open source, so it's an oss job. Opinions @simonv3?

**Comment by patdavid** [comment]
Is the purpose of the job board clearly defined somewhere for reference?  It might help to direct any entries to a definition for clarity.

**Comment by elioqoshi** [comment]
Not sure if @simonv3 is available. This is an interesting use case as we probably never thought of it. Maybe we need to set clearer rules about the Job Board if we think that this request should not be on the Job Board.

**Comment by belenbarrospena** [comment]
@patdavid it probably isn't anywhere: we should consider writing it down and publishing it somewhere. 

I think the idea of the jobs board was creating a space to bring together FOSS projects who need design contributions with designers who would like to contribute to FOSS. During our first FOSDEM, a lot of developers asked us where to find designers interested in contributing: that question drove the creation of the jobs board. 

Given the above, it all boils down to the "simple" ;) question of what is a FOSS project. I think that "a personal portfolio, to publicize my skills" cannot be considered a FOSS project, and that's why I asked about the PR approval. 

I am not asking that we revert it: I brought it up because these discussions are good. They help us clarify what we are trying to do.

**Comment by evalica** [comment]
I also find this 'job' strange and it not related to any open source project, product or community. The intent of usage is very limited / personal.

**Comment by jancborchardt** [comment]
Fully agree with @belenbarrospena here.

Also, just to be safe and becausr we don't need to rush things, on all repos we should enable that 2 people need to approve a pull request. :)

**Pull request merged**
