### PR TITLE
New Job - Find a solution to improve the design of FreeCAD

### PR DESCRIPTION
**Pull request by staticmanapp**
Dear human,

Here's a new entry for your approval. :tada:

Merge the pull request to accept it, or close it to send it away.

:heart: Your friend [Staticman](https://staticman.net) :muscle:

---
| Field        | Content                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               |
| ------------ | --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- |
| status       | searching                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             |
| date_posted  | 2017-03-03                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            |
| layout       | jobs                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  |
| organization | FreeCAD                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               |
| org_url      | http://freecadweb.org/                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                |
| title        | Find a solution to improve the design of FreeCAD                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      |
| role         | Designer                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              |
| compensation | gratis                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                |
| description  | The FreeCAD project does not care enough about design. For example, the section about UX on our forum contain 600 posts compare to the 25 000 posts of the developer corner. A simple look at the aspect of the forum or the web site will convince you we need more designer in charge.
So we need to change, but we don't know how. The mission of the job is to proposed solutions to improve the current situation. This could be achieved by posting a list of action to perform, an image, a philosophy to preach, a formation to proposed, an article to read, I do not know. We just need help.
The idea of this job offer come after watching the great bunch of presentations made by the OpenSourceDesign community at the Fosdem 2017. You are awesome. |
| skills       | The deliverables will be a solution to the problem describe in the job description.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   |
| how_to_apply | To apply go to the post on our forum.
https://forum.freecadweb.org/viewtopic.php?f=34&t=21063,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       |
| tags         | Non-visual software design, help!                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     |
| date         | 2017-03-03T18:41:30.340Z                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              |
| timestamp    | 1488566490                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            |

### CODE REVIEW

**Comment by elioqoshi** [comment]
I can offer branding/visual identity help and EVENTUALLY web design for the landing page. Latter would take some time though :)

**Comment by simonv3** [comment]
@elioqoshi I don't know if they'll get notified about this - might be worth reaching out in the forum. 

It might be an idea to let someone supply their GitHub handle to allow them to be notified of the PR creation.

**Comment by normandc** [comment]
Branding/visual identity is not what's needed. The original poster made this request without talking to the community first. Therefore this request is very poorly worded and does not represent the wishes of the FreeCAD community.

**Comment by simonv3** [comment]
@normandc, we're sorry to hear that! Feel free to submit a PR to change it, or changing the status to closed.

**Comment by AjinkyaDahale** [comment]
@simonv3, just an idea, would you consider documentation requests?

**Comment by normandc** [comment]
@simonv3, thanks. I am only one member of this community, it's not my place to decide on this. The following is my personal opinion. I felt the PR wording made us look like we're hapless. It's insulting. As for the number of posts in the UX/UI Design forum, well duh, it's a very new forum where we started to group UI-related discussion, previously and for years they were posted in the other development forums, and not all of them were migrated (it would be a heck of a job to locate and move them).

While it's true that FreeCAD does need work to improve its general user interface, due to the nature of its development this is not something that can be improvised, and IMHO it will require people willing to familiarize with the project first, get to know its community, and to commit in the long term.

**Comment by simonv3** [comment]
@normandc I think those are all very reasonable things. Keep us posted on what the FreeCAD community decides, and again, feel free to edit the posting. If you (as a community) feel that it should be taken down, it's fairly easy to remove it. I can help with that if needed. 

I'm also interested in what you think OSD can do better here - should there be some verification that the posting speaks for the community? Up to now most of our posting have been done by leaders in the project, usually after confirmation from others (or at least, that's what I have gathered). My hesitation with the verification is that it will create more work for this board already run by volunteers. I'd be interested in hearing your thoughts on that.

**Comment by m1guelpf** [comment]
@simonv3 Opened a PR at #184 to revert this change.

**Comment by Mika38** [comment]
Dear all,
I created this new job, and I should probably not. I would like to see this post remove from your website. I think it is the best way to quickly fix what I did. I trying to repair what I consider now a mistake, as I told on the FreeCAD forum.
I'm trying to improve the design of FreeCAD, but even if my intention was good, the way I implement it was wrong. I should have definitively spoke first about my idea on the forum, get approved, then post the job offer.  
By the way, I found weird that I have to create a Github account to remove this job offer. The possibility to do it from the open source design website could be interesting (like in my case), but also can create unnecessary complexity. I'm just used to website with identification and account.
@simonv3 I'm happy to exchange with you if want feedback.

Best regards,
Mika

**Comment by simonv3** [comment]
@Mika38 Have a look at #184.

**Comment by simonv3** [comment]
#184 has been merged and this file is now deleted.

**Pull request merged**
