### PR TITLE
 Creaate a logo for open source Phanbook

### PR DESCRIPTION
**Pull request by duythien**

### CODE REVIEW

**Comment by simonv3** [comment]
I'm going to merge this even though @elioqoshi has already said they're interested. 

Other people might be too :)

**Comment by bnvk** [comment]
@duythien heya, awesome submission. I think this is (unless I
missed something) the first submission that achieved precisely
what I hoped this job board could do- helping bring great
designers to free software with being able to not starve in the
process. Thank you for submitting it :) @simonv3 thanks for
merging!

**Comment by simonv3** [comment]
@bnvk @elioqoshi has actually been reaching out to a number of the postings on here as far as I'm aware (he reached out to the OF people is how I know).

**Comment by elioqoshi** [comment]
Having said that, I do not want to take everything over here, so if anyone else stumbles here, feel free to have a go too!

**Comment by elioqoshi** [comment]
@duythien first proposal here. I used a Mockingbird for the logo. The idea behind was that mockingbirds are also called colibri, and "libri" comes from "libre" as in free :)

Let me know what you think
draft-01

**Pull request merged**
