### PR TITLE
New Job - Create a logo for Recase project

### PR DESCRIPTION
**Pull request by staticmanapp**
Dear human,

Here's a new entry for your approval. :tada:

Merge the pull request to accept it, or close it to send it away.

:heart: Your friend [Staticman](https://staticman.net) :muscle:

---
| Field        | Content                                                                                                                                                                                                                                     |
| ------------ | ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- |
| status       | searching                                                                                                                                                                                                                                   |
| date_posted  | 2017-07-09                                                                                                                                                                                                                                  |
| layout       | jobs                                                                                                                                                                                                                                        |
| organization | Recase                                                                                                                                                                                                                                      |
| org_url      | https://github.com/sobolevn/recase                                                                                                                                                                                                          |
| title        | Create a logo for Recase project                                                                                                                                                                                                            |
| role         | Logo design                                                                                                                                                                                                                                 |
| compensation | gratis                                                                                                                                                                                                                                      |
| description  | `Recase` is a small `elixir` project to convert string from any case to any case.
It now supports `camelCase`, `UpperCase`, `snake_case` and `kebab_case`.

We need a branding: just a simple logo to picture repo's main functionality. |
| skills       | Logo in HiRes.                                                                                                                                                                                                                              |
| how_to_apply | Nikita Sobolev - mail@sobolevn.me
Or github: https://github.com/sobolevn,                                                                                                                                                                  |
| tags         | logo, elixir                                                                                                                                                                                                                                |
| date         | 2017-07-09T09:53:37.981Z                                                                                                                                                                                                                    |

### CODE REVIEW

**Comment by sobolevn** [comment]
Wow, this works really well!

**Comment by m1guelpf** [comment]
@sobolevn Merged!

**Comment by simonv3** [comment]
It's here: http://opensourcedesign.net/jobs/jobs/2017-07-09-create-a-logo-for-recase-project

:)

**Comment by sobolevn** [comment]
@m1guelpf @simonv3 this one is now closed. 

Looks awesome: https://github.com/sobolevn/recase
Thanks to @gyanl

**Pull request merged**
