### PR TITLE
Added `awesome-cryptography` twitter account job

### PR DESCRIPTION
**Pull request by sobolevn**
[`awesome-cryptography`](https://github.com/sobolevn/awesome-cryptography) is looking for a logo for our [twitter account](https://twitter.com/awe_crypto_bot).

See job description for details.

### CODE REVIEW

**Comment by simonv3** [comment]
Awesome! Live here: http://opensourcedesign.net/jobs/jobs/2016-07-06-awesome-cryptography-twitter-logo

**Comment by elioqoshi** [comment]
Something veryyy simple. Let me know :)

**Comment by sobolevn** [comment]
Wow, that's a very nice one! I really like your style. Accepted.

**Comment by sobolevn** [comment]
Can you also help me with the background? Sorry, not to mention earlier. I didn't know it even existed.

**Comment by elioqoshi** [comment]
@sobolevn thanks! And sure, what do you need?

**Comment by sobolevn** [comment]
Here's the screenshot: 


I want to reply that blue line with an themed image. Do you have any ideas?

**Comment by elioqoshi** [comment]
Sorry, I didn't understand that, can you be a bit more specific please?

Also, you should make the icon bigger in the profile picture.

**Comment by simonv3** [comment]
@elioqoshi I believe that @sobolevn is looking for some thoughts and design advice for the header image in Twitter (the big blue thing at the top of the page).

**Comment by sobolevn** [comment]
@simonv3 exactly! But I don't have any ideas about what it can be. Since I don't have much experience with twitter.

@elioqoshi Thanks, I have enlarged it.

**Comment by elioqoshi** [comment]
@sobolevn I'd personally suggest a photo. Check out these Public Domain ones here:
https://unsplash.com/?grid=multi

**Comment by bnvk** [comment]
@sobolevn neat projects and efforts :+1: I had been trying to get something similar to "Awesome Cryptography" going with [modernpgp](https://github.com/modernpgp), but obviously smaller in scope!

**Comment by sobolevn** [comment]
@bnvk thanks!  Do you have any cool projects in mind which could be added? Looking forward!

**Pull request merged**
