### PR TITLE
Update 2020-05-26-new-logo-to-go-with-major-app-update.md

### PR DESCRIPTION
**Pull request by keunes**
Correct email address & improve formatting (move relevant links)

### CODE REVIEW

**Comment by keunes** [comment]
Hi @AnXh3L0 & @belenbarrospena
Given the broken rendering and following feedback from AntennaPod's lead developer, I made changes. Would you mind reviewing these also? Many thanks 🙏

**Comment by keunes** [comment]
Thanks @ei8fdb for spotting that typo! Two new reviews required 😇

**Comment by ei8fdb** [comment]
Good luck with the search!

**Comment by keunes** [comment]
Thanks @ei8fdb! If you have further ideas to disseminate the call they're most welcome ;)

**Pull request merged**
