### PR TITLE
New Job - mochajs.org facelift and logo

### PR DESCRIPTION
**Pull request by staticmanapp**
Dear human,

Here's a new entry for your approval. :tada:

Merge the pull request to accept it, or close it to send it away.

:heart: Your friend [Staticman](https://staticman.net) :muscle:

---
| Field        | Content                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          |
| ------------ | ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------ |
| status       | searching                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        |
| date_posted  | 2017-10-01                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       |
| layout       | jobs                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             |
| organization | Mocha                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            |
| org_url      | https://mochajs.org                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              |
| title        | mochajs.org facelift and logo                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    |
| role         | logo, branding, site design                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      |
| compensation | paid                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             |
| description  | Mocha is a testing framework, and [the most depended-upon project](https://libraries.io/search?order=desc&platforms=NPM&sort=dependents_count) in the npm ecosystem. 

...but our site was built in (literally) 2011.  That said, this old horse gets about 200k page hits a month over the past year (it's a single page).

Our site should still be focused on documentation (tutorials and dry API docs), but would also like to add a "news" or "blog" section.  Let's move away from "one huge page" and organize it properly.  The site should be responsive, accessible and lightweight.

A new logo and/or logotype would be desirable. Our tagline is "simple, flexible, fun"; ultimately the design of the logo and site should reflect that.  We plan to put the logo(s) on shirts, stickers, and swag.

Donations the project has received could pay for the work.  We are all volunteers, but we don't have enough time nor skill to pull this off ourselves.  You *can* do this for free, but we want you to be motivated! |
| skills       | This is off the top of my head, but happy to discuss.

- A primary "hexagon-style" logo in SVG format ([examples](http://hexb.in/))
- An alternate logo or logotype in SVG format
- Color palette (think "brown") "swatches" in whatever format
- Markup and styles to replace mochajs.org.  We'd like these "layouts":
  - Landing page
  - Individual documentation page
  - Individual blog/news post (if different than previous)
  - List of blog posts (should probably not be front page)

Our team would be responsible for putting the content where it belongs, but if anyone knows a technical writer, the content itself needs some love!!                                                                                                                                                                                                                                                                                                                                                                                |
| how_to_apply | Contact Christopher Hiller on [Twitter](https://twitter.com/b0neskull) or email [boneskull@boneskull.com](mailto:boneskull@boneskull.com),[GitHub project](https://github.com/mochajs/mocha)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     |
| tags         | logo, site design, documentation                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 |
| date         | 2017-10-02T05:40:27.160Z                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         |
| timestamp    | 1506922827                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       |

### CODE REVIEW

**Comment by boneskull** [comment]
(this was from me)

**Comment by m1guelpf** [comment]
Here you go @boneskull

**Comment by milapbhojak** [comment]
Hi community,

I would like to work in this. Is there a timeframe to deliver the final designs?

**Comment by AnXh3L0** [comment]
Hi,

I would also like to work on this.

**Pull request merged**
