### PR TITLE
RadioWitness.io - alpha release branding

### PR DESCRIPTION
**Pull request by rhodey**
added job posting for https://radiowitness.io alpha release branding.

### CODE REVIEW

**Comment by elioqoshi** [comment]
We can take this on, thanks for posting!

**Comment by elioqoshi** [comment]
draft-02

Here is my first go, let me know what you think :)

**Comment by elioqoshi** [comment]
Font is Exo 2, which is an open font of course

**Comment by rhodey** [comment]
Love it so far :) the left half of the third asset would make an especially great favicon. I'd love to work with you, at this point do I change the job `status` from `searching` to something else?

I'm interested in experimenting with the color a bit, like this blue is a perfect neutral but I wonder if a green could work too. Some people are freaked out by the idea of bringing transparency to law enforcement so trying to portray safe feelings wherever possible.

Specifically we'll need the following renderings:

+ Twitter header: 1500x500
+ Patreaon header: 1600x400
+ Twitter/Patreon/Github/etc profile photo: 500x500
+ Standard favicon.ico rendering

Thanks for responding so quickly!

**Comment by elioqoshi** [comment]
@rhodey Happy you like it! Green is a bit difficult to pull of unless it's about something nature related. In this case, as it is about law enforcement, blue is the closest choice. However, as the dark blue used by police is rather indimidating, I went for a lighter and friendlier one. This should do the trick.

Here is how it looks on green (I don't like it)
green-01

**Comment by elioqoshi** [comment]
Here are the files you requested with the original colors. I think this looks really well (also with the abstract pattern to disrupt it a bit. Let me know if you like this and I can export you the source files as well. 
radiowitness_favicon
radiowitness_patreon
radiowitness_profile picture
radiowitness_twitter

**Comment by rhodey** [comment]
Thanks for including the green renderings and the sizes that I asked, I
agree the blue looks better :)

I'm away from my laptop now but I'll test these out on Twitter/Github/etc
when I return.

I can send you the $120 via Venmo or PayPal or Bitcoin, whatever you
prefer. The project is very new so currently there is no contributors-type
page but I hope to create one soon. For now I can definitely add you to the
'radiowitness' github organization if you'd like.

-- rhodey

**Comment by elioqoshi** [comment]
@rhodey Sure, happy you like them!

You can find all files here, including source files (sorry for Dropbox, my ownCloud is striking right now)
https://dl.dropboxusercontent.com/u/62482708/RadioWitness.zip

PayPal is fine: elioqoshi@ura.al

Regarding credits, don't stress it until you get there, the project is very promising and you should take your time :)
Happy I could help!

Cheers,
Elio

**Comment by rhodey** [comment]
sorry for the delay, sent!

**Comment by rhodey** [comment]
@bnvk how should I update the status of this job posting?

**Comment by simonv3** [comment]
Went ahead and closed it 👍  https://github.com/opensourcedesign/jobs/commit/8e6d6f15a3d130171223fb72371c67e1365dd1f4

**Comment by bnvk** [comment]
@elioqoshi nice job banging that out with a such fast turnaround. Thanks @rhodey for helping generate an OSD success story :smile:

**Comment by rhodey** [comment]
Yeah really the turnaround time on this was amazing, exactly what we needed
with our timeframe of everything this week.

I'll be sure to send our future requests onto OSD once we hit our next
release/branding cycle 👍👍👍

-- rhodey

**Comment by ameellio** [comment]
I’m nodding along to see @rhodey, @nvk, and @elioqoshi in a thread.

Waves and re-lurks.

~Ame

**Pull request merged**
