### PR TITLE
Update and rename YYY-MM-DD-ChooseAJobTitle.md to 2016-11-28-Logo-for…

### PR DESCRIPTION
**Pull request by ij0n**
…-Libreflip.md

### CODE REVIEW

**Comment by gillisig** [comment]
Thanks @ij0n !

**Comment by elioqoshi** [comment]
@ij0n Do you still need this? I might be available to help.

**Comment by ij0n** [comment]
Hey elioqoshi,

thank you for asking! I made these Logos myself, someone from here gave me some opinions during the process.

logo-name-shape-raster-black
logo-shape-raster-black
logo-name-bw
logo-bw

Please feel free to improve them - i am not perfectly happy with them, but for now they feel like a "damn, stop fiddling with the logo, get on with it, build the machine, the logo is 'good enough'"

The Logo right now is just "good enough" but not "perfect". So if you are willing and able to change these little details to make them perfect, i would be VERY thankful!

Cheers
Ijon

**Comment by elioqoshi** [comment]
@ij0n Sure. Gave this a go. Also used Overpass as a font here (which is an open font).

What do you think?

**Comment by ij0n** [comment]
The shape that looks like a diamond is actually the shape of the core part of the machine that does the pageturning. I somehow wanted this part to be part of the logo, as it is the main part of the "invention" and i think it could be a symbol.

The DIY Bookscanner Community has had several "standard" designs, developed by different people. Some of them were available as Kits, others just as CAD-Models or Tutorials. I am trying to develop the first "new standard" bookscanner that can turn the pages automatically. There are one or two opensource pageturning bookscanner-designs out there but none of them really made a breakthrough in the community, because of technical complexity. So this is an attempt to simplify the whole design so much that the build-complexity is comparable to assembling a 3D-Printer Kit.

Here is a technical drawing of the machine:

complete-scanner-rev2-scaled

**Comment by elioqoshi** [comment]
Got it, thanks for the background, this helped. Let me get back to this with another proposal

**Pull request merged**
