### PR TITLE
New Job - Face-lifting: New design for Angular Material web application

### PR DESCRIPTION
**Pull request by staticmanapp**
Dear human,

Here's a new entry for your approval. :tada:

Merge the pull request to accept it, or close it to send it away.

:heart: Your friend [Staticman](https://staticman.net) :muscle:

---
| Field        | Content                                                                                                                                                                                                                                                                                                                                                                                 |
| ------------ | --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- |
| status       | searching                                                                                                                                                                                                                                                                                                                                                                               |
| date_posted  | 2018-07-30                                                                                                                                                                                                                                                                                                                                                                              |
| layout       | jobs                                                                                                                                                                                                                                                                                                                                                                                    |
| organization | Backbone                                                                                                                                                                                                                                                                                                                                                                                |
| org_url      | https://backbone.forcrowd.org                                                                                                                                                                                                                                                                                                                                                           |
| title        | Face-lifting: New design for Angular Material web application                                                                                                                                                                                                                                                                                                                           |
| role         | Web design                                                                                                                                                                                                                                                                                                                                                                              |
| compensation | paid                                                                                                                                                                                                                                                                                                                                                                                    |
| description  | Backbone is an experimental public web api application. Users can create a backend application (database / web api) through Backbone. It aims to help developers to create app prototypes for their front-end applications.

It has been developed by Angular Material (and Material design). It needs some face-lifting, colors, design, especially for create/manage web api pages. |
| deliverables | . Primary: A new design of the web app, mobile-friendly if easy to achieve: colors, menu design etc.
. Secondary: Ideas to fill the landing page?                                                                                                                                                                                                                                      |
| how_to_apply | Serkan Holat - serkan.holat@forcrowd.org,Github repo: https://github.com/forCrowd/Backbone
                                                                                                                                                                                                                                                                                            |
| tags         | web app design, user-friendly                                                                                                                                                                                                                                                                                                                                                           |
| date         | 2018-07-30T09:05:14.109Z                                                                                                                                                                                                                                                                                                                                                                |

### CODE REVIEW

**Comment by coni2k** [comment]
Ola! Just in case, I'm the contact person of this post.

**Comment by ei8fdb** [comment]
Hi @coni2k one question:

When you say "face-lift" you mean of how the website looks? Or face-lift of how the software actually works?

I'm wondering if it could help adding an "interaction design" tag to make it clearer to anyone interested in the work.

**Comment by jancborchardt** [comment]
Merged it, please open a follow-up pull request if you want to make any improvements to the job. :)

It will also show up in the forum soon: https://discourse.opensourcedesign.net/ – discussions related to the job itself (and solutions) should be done there. :)

**Comment by coni2k** [comment]
Great, thanks @jancborchardt. Then, when it's on, we can continue on the forum for the rest..

**Comment by jancborchardt** [comment]
@coni2k and it’s in the forum at https://discourse.opensourcedesign.net/t/jobs-face-lifting-new-design-for-angular-material-web-application/704 :)

The discussion from the forum is also embedded in the job posting itself so all comments will show up: https://opensourcedesign.net/jobs/jobs/2018-07-30-

**Pull request merged**
