### PR TITLE
New Job - Frontend & branding for ComposerCI

### PR DESCRIPTION
**Pull request by staticmanapp**
Dear human,

Here's a new entry for your approval. :tada:

Merge the pull request to accept it, or close it to send it away.

:heart: Your friend [Staticman](https://staticman.net) :muscle:

---
| Field        | Content                                                                                                                                                                                                                          |
| ------------ | -------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- |
| status       | searching                                                                                                                                                                                                                        |
| date_posted  | 2017-04-28                                                                                                                                                                                                                       |
| layout       | jobs                                                                                                                                                                                                                             |
| organization | ComposerCI                                                                                                                                                                                                                       |
| org_url      | mailto:composerci@miguelpiedrafita.com                                                                                                                                                                                           |
| title        | Frontend & branding for ComposerCI                                                                                                                                                                                               |
| role         | Designer                                                                                                                                                                                                                         |
| compensation | gratis                                                                                                                                                                                                                           |
| description  | ComposerCI is a Composer Continous Integration tool, that send a Pull Request every time a Composer dependency you use is updated.
We are starting the development, so we can use any frontend framework you are familiar with! |
| skills       | If you design the frontend, scss, javascript and html files should be delivered.
If you do the branding, svg & png files for the logo, the font and main colors.                                                                |
| how_to_apply | Send a mail to composerci@miguelpiedrafita.com,                                                                                                                                                                                  |
| tags         | frontend, branding, logo, design, gratis, free                                                                                                                                                                                   |
| date         | 2017-04-28T13:28:04.234Z                                                                                                                                                                                                         |

### CODE REVIEW

**Comment by simonv3** [comment]
👍  thanks @m1guelpf!

**Comment by m1guelpf** [comment]
@simonv3 You should really write a document about who can merge PR's in each repository...

**Comment by simonv3** [comment]
Hmm, maybe something to add to the by-laws? 

Would you want to draft something?

**Comment by m1guelpf** [comment]
@simonv3 I would love to, but I don't know the information (That's why I asked...)

**Comment by simonv3** [comment]
I think there's nothing concrete at the moment, so there is no information. 

The existing by-laws have some similar stuff already outlined: opensourcedesign.net/by-laws/

I imagine that most changes should be put in a PR. It's best practice to then ping a couple of people to review it and give them a couple of days. If no one reviews within a handful of days you can merge it yourself.

**Comment by elioqoshi** [comment]
@m1guelpf Can do branding again here unless someone else wants to :)
Someone else needs to take over the frontend part however

**Comment by m1guelpf** [comment]
@elioqoshi Finally decided I'd do the frontend myself. Now only branding is needed :smile:

**Comment by elioqoshi** [comment]
Cool, I will get back to it

**Comment by elioqoshi** [comment]
@m1guelpf Here we go, what do you think?

cc1-01

**Comment by m1guelpf** [comment]
@elioqoshi Awesome! I've given you push access to the https://github.com/composerci/branding repo

**Comment by elioqoshi** [comment]
@m1guelpf it should indicate a "CI" if you look closely :)

**Comment by m1guelpf** [comment]
@elioqoshi That's a very good idea!

**Comment by m1guelpf** [comment]
@elioqoshi You have now push access to to the [composerci/branding](https://github.com/composerci/branding) repo to upload the logos!

**Comment by m1guelpf** [comment]
@elioqoshi We have moved to DependenCI, the new branding repo is [dependenci/branding](https://github.com/dependenci/branding)

**Comment by m1guelpf** [comment]
@elioqoshi Could you please update the logo text to show DependenCI instead of ComposerCI?
Thank you!

**Comment by m1guelpf** [comment]
@elioqoshi Any updates?

**Pull request merged**
