### PR TITLE
Basic Income through Group Income — Frontend Lead

### PR DESCRIPTION
**Pull request by taoeffect**
okTurtles Foundation job listing for [Group Income](https://groupincome.org) — Voluntary Basic Income — Frontend Lead.

### CODE REVIEW

**Comment by gillisig** [comment]
Thanks @taoeffect you can view the job here now: http://opensourcedesign.net/jobs/jobs/2016-10-10-the-best-node-mvc-framework-crocodilejs

**Comment by gillisig** [comment]
Hmm for some reason this isn't appearing on http://opensourcedesign.net/jobs/

@simonv3 you had some problem like this yesterday right? any idea what is causing this one?

**Comment by myckyc** [comment]
The problem was "a newline at the beginning of the file"

**Comment by gillisig** [comment]
Thanks @myckyc. I guess we are having some other issue now :/

**Comment by gillisig** [comment]
Okay I fixed it. This time there was a " /" after "status: searching"

Man this thing is really sensitive to typos!

**Comment by simonv3** [comment]
Hopefully we can figure something better out that will automate the PR process! #91.

**Comment by taoeffect** [comment]
Woah, sorry I didn't notice that, but this is incredible support I have to say, didn't even need to ask! 😄 👍

**Comment by gillisig** [comment]
@taoeffect no problem. Happy to help. Also this job sounds very interesting. I would be interested in applying but unfortunately I'm more on the design side of front-end and less on the security development side ;)

**Comment by simonv3** [comment]
This looks rad, thanks for doing the PR and sharing it @taoeffect!

**Pull request merged**
