### PR TITLE
Etherpad Job posting

### PR DESCRIPTION
**Pull request by JohnMcLear**
A job posting for Etherpad

### CODE REVIEW

**Comment by jancborchardt** [comment]
Yeah, this is damn awesome! Glad to have an Etherpad job posting up on the board, and cool that you’re looking for design help.

:+1:

**Comment by jancborchardt** [comment]
You’re also welcome in our IRC channel #opensourcedesign by the way.

**Comment by JohnMcLear** [comment]
Thank Mikael Korpela for the heads up.

I'm already in the IRC chan :)

**Comment by jancborchardt** [comment]
Awesome, thanks @simison :) (Did I not invite you to the organization previously!?)

**Pull request merged**
