### PR TITLE
New Job - Frontend polishing

### PR DESCRIPTION
**Pull request by staticmanapp**
Dear human,

Here's a new entry for your approval. :tada:

Merge the pull request to accept it, or close it to send it away.

:heart: Your friend [Staticman](https://staticman.net) :muscle:

---
| Field        | Content                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  |
| ------------ | ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------ |
| status       | logged-in                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                |
| date_posted  | 2017-11-10                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               |
| layout       | client                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   |
| organization | Identihub                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                |
| org_url      | https://demo.identihub.co                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      |
| title        | Frontend polishing                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       |
| role         | Web Design, Frontend, UX                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 |
| compensation | paid                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     |
| description  | Identihub is free and open source software which lets you host your own branding and visual assets and reshare them easily. It allows for SVG to PNG conversion in any given resolution, embedding and linking to assets and organizing your projects within your organization. The project is open source under AGPLv3: https://github.com/uracreative/identihub

We currently are in need for someone who can improve Identihub's UX by adding more feedback menus and interactions, redesign modal menus and the main side bar for assets. Currently Identihub is not really working well on mobile, so making it responsive is also needed. Identihub is ReactJS in the Frontend and Laravel (PHP) in the Backend. |
| deliverables | General UX improvements in the software are needed, including:
Sidebar of Assets
Modal Menus
Feedback Messages
Error Messages

Generally some User Research would be also appreciated to understand what's the best path going forward.                                                                                                                                                                                                                                                                                                                                                                                                                                                                            |
| how_to_apply | Elio,https://github.com/uracreative/identihub
https://ura.design
https://demo.identihub.co                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             |
| tags         | Frontend, UX, CSS, ReactJS                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               |
| date         | 2017-11-10T21:09:38.305Z                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 |
| category     | clients                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  |
| permalink    | /clients/kid                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             |
| active       | my-fix                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   |

### CODE REVIEW

**Comment by elioqoshi** [comment]
I posted this, so would appreciate someone reviewing it :)

**Comment by elioqoshi** [comment]
@simonv3 may I ask why the post was unlisted from the Discourse?

**Comment by simonv3** [comment]
I've been unlisting all job postings, but maybe it makes sense to only unlist the older ones (like, there was one automatically created for the Mozilla Design thing, which was from 2016 and is now at the top of the list).

**Comment by tessgadwa** [comment]
Elio Quoshi, are you affiliated with the company posting? If so I have some
questions -- pls reply to me off-list.

Thanks,
Tess

Tess.gadwa@yesexactly.com

**Comment by elioqoshi** [comment]
@simonv3 Right, makes sense!

@tessgadwa If you have any questions, please send me an email, that's the reason I posted the job :)
elio@ura.design

**Pull request merged**
