### PR TITLE
New Job - Logo and icons review of our remote desktop client

### PR DESCRIPTION
**Pull request by staticmanapp**
Dear human,

Here's a new entry for your approval. :tada:

Merge the pull request to accept it, or close it to send it away.

:heart: Your friend [Staticman](https://staticman.net) :muscle:

---
| Field        | Content                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           |
| ------------ | ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- |
| status       | searching                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         |
| date_posted  | 2018-03-21                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        |
| layout       | jobs                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              |
| organization | Remmina                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           |
| org_url      | http://www.remmina.org                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            |
| title        | Logo and icons review of our remote desktop client                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                |
| role         | Logo and application icons design                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 |
| compensation | paid                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              |
| description  | Remmina is                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        |
| deliverables | A feature rich Remote Desktop Application for Linux and other Unixes.
We'd like to review our logo, the R that symbolise a Network connection and we'd like a complete redesign of our in app icons (see screen shots). We were thinking a rabbit shaped R to symbolise the speed, the jumping, the tunnel digged by this rabbit named Remmina, that will be our mascot. For the icons we'd like something, or just an extention, similar to feathericons,in vector and all the typical icon sizes till 512 px. We have a tight budget but can offer some good visibility and support. As I was saying an extention of the feathericons is fine. |
| how_to_apply | Antenore@simbiosi.org,http://github.com/FreeRDP/Remmina                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           |
| tags         |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   |
| date         | 2018-03-21T18:04:28.583Z                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          |

### CODE REVIEW

**Comment by elioqoshi** [comment]
@antenore Would like to help on this together with @AnXh3L0 if you haven't found some yet :)

**Comment by antenore** [comment]
With pleasure! Thanks.
 I add @giox069 to the discussion

**Comment by antenore** [comment]
@elioqoshi @AnXh3L0 I'd like to add some screenshots to better highlight what we are looking for.
Is this PR the right place or the MD file? Sorry I'm new to this

**Comment by elioqoshi** [comment]
@antenore  We can keep the discussion here, it's not a set in stone process, feel free :)

**Comment by antenore** [comment]
Ok, thanks. I saw the job posting here and I'm authenticated.
Just in case if you prefer I can post there

**Comment by antenore** [comment]
Main Remote connection Window toolbar (vertical)

image

Can be horizontal as well

Currently the logo is

https://github.com/FreeRDP/Remmina/blob/next/remmina/desktop/scalable/apps/remmina.svg 

The Protocol icons are:

remmina-rdp
remmina-rdp-ssh
remmina-spice
remmina-vnc
remmina-vnc-ssh
remmina-tool
remmina-nx

The are placed under each directory here https://github.com/FreeRDP/Remmina/tree/next/remmina-plugins ( I don't have the vector one)

Those protocol Icons are showed in the Main Remmina Window, that looks like this:

image

Finally, the only icon we still like,is the desktop status icon

image

As I was saying we like quite a lot the feathericons, as we can easily switch from light to dark and it missis just few icons of the first set, but we are really really open to any proposal.

Regarding the Rabbit as well, we thought about it because we like the animal and the analogies of jumping, tunnel, fast, etc and that The R could be maybe worked out to looks like a rabbit.

Again, we are really open to discussion.

Thanks again and don't hesitate to asks for any more details

**Comment by elioqoshi** [comment]
@antenore Thanks for the detailed brief! Do you have the source files of these icons somewhere? Also, is there any style needed for the icons? I see that the style is GNOME Adwaita. Do you want to go flat? Or do you want to stay consistent with GNOME visual language?

@bertob does design for GNOME and I think his input would be valuable as well

**Comment by antenore** [comment]
@elioqoshi 

Except the png files not, just for the logo (main icon) we have the sources.

https://github.com/FreeRDP/Remmina/tree/next/remmina/desktop
https://github.com/FreeRDP/Remmina/tree/next/remmina/icons

and inside each of the directories over here https://github.com/FreeRDP/Remmina/tree/next/remmina-plugins you can find each protocol icons (except sftp, that is in the main icons folder).

Remmina is used by thousands users, so we need something that can well adapt to most themes. I'd like as well an expert advice, I hope @bertob can help.

In general we uses as much as possible stock icons, like the terminal one I've cited earlier, but in most cases we need custome icons, like the above ones, that's why we were thinking to use as much simple as possible (but still beautiful ;-) ) icons that we can provide in different sizes (up to 512) and 2 colors (white/light and black/dark).

The new Firefox icons I think it's a good example.

Sorry I really lack the wisdom and the knowledge to explain better than this

**Comment by elioqoshi** [comment]
Okay, makes sense @antenore 

With Firefox icons do you mean these: https://design.firefox.com/icons/viewer/

It would be helpful to have a list of all icons listed as there is not great overview in git repo to determine that.

For the logo, would you be open to a redesign?

**Comment by antenore** [comment]
Yes, the one of the Firefox interface menu

**Comment by antenore** [comment]
Regarding the logo, yes, no problems

**Comment by antenore** [comment]
Sorry I'm jumping here and there... I'll answer about the icons later, in some hours hopefully, with as much details as I can

**Comment by elioqoshi** [comment]
Sure, let's get started with the logo first :)

**Comment by antenore** [comment]
I'm working on the icon report. Just one note the big screenshot I've shared is old, sorry. That's why maybe you are confused about the icons

**Comment by antenore** [comment]
Before a interface tour, so that you get the big picture, than below you can see a table with all the icons.

## Starting Remmina open a main window that looks like this:

image

1. On the left upper corner there is the "Logo" icon
2. The + just below is a stock icon that is taken from the installed theme (we can keep or change based on your advice) .
3. On the right of the RDP button there is another stock icon, in the search form. (no need in my opinion).
4. In the main window you can see the stock icons for the folders and each protocol icon, again for the stock icons I'm not sure there's need to change them.

## Opening a connection to one of those profile, create a new window that looks like this one

image

1. On the left you can see a toolbar that can be moved around and it contains the following icons (most can be greyed if not used).
2. Resize to fit window icon
3. Toggle fullscreen
4. Switch Tab (to change the focus to another tab)
5. Dynamic resolution (if supported)
6. Grab keyboard (Keystrokes are sent only to the remote server)
7. Plugin tools (copy and paste, macros, etc)
8. Screen shot tool
9. Minimize the window (the container of the remote connection/desktop)
10. Disconnect.

## Editing or creating a new profile open a window like this

image

All the icons, except the protocol one, are stock icons (same thoughts as above).  
I was thinking even to remove those icons (@giox069 ? )

Now the hardest part the icon table

## Protocol icons

| Icon | Description | Context | Source |
|----------------------------------------------------------------------------------------------------------------------|-------------------------------------|-----------------------------------------------------|-------------------------------------------------------------------------------------------------------------------------------------------|
| remmina-rdp | RDP protocol Icon | Main Window, Profile editor, Connection Window/Tab. | https://github.com/FreeRDP/Remmina/blob/next/remmina-plugins/rdp/22x22/emblems/remmina-rdp.png |
| remmina-rdp-ssh | RDP over SSH tunnel protocol Icon | Main Window, Profile editor, Connection Window/Tab. | https://github.com/FreeRDP/Remmina/blob/next/remmina-plugins/rdp/22x22/emblems/remmina-rdp-ssh.png |
| remmina-spice | Spice protocol Icon | Main Window, Profile editor, Connection Window/Tab. | https://github.com/FreeRDP/Remmina/blob/next/remmina-plugins/spice/22x22/emblems/remmina-spice.png |
| NOT YET IMPLEMENTED | Spice over SSH tunnel protocol Icon | Main Window, Profile editor, Connection Window/Tab. | NOT YET IMPLEMENTED |
| remmina-vnc | VNC protocol Icon | Main Window, Profile editor, Connection Window/Tab. | https://github.com/FreeRDP/Remmina/blob/next/remmina-plugins/vnc/22x22/emblems/remmina-vnc.png |
| remmina-vnc-ssh | VNC over SSH tunnel protocol Icon | Main Window, Profile editor, Connection Window/Tab. | https://github.com/FreeRDP/Remmina/blob/next/remmina-plugins/vnc/22x22/emblems/remmina-vnc-ssh.png |
| remmina-tool | Exec (local command) Icon. | Main Window, Profile editor, Connection Window/Tab. | https://github.com/FreeRDP/Remmina/blob/next/remmina-plugins/exec/22x22/emblems/remmina-tool.png |
| remmina-nx | NX (No machine) protocol Icon | Main Window, Profile editor, Connection Window/Tab. | https://github.com/FreeRDP/Remmina/blob/next/remmina-plugins/nx/22x22/emblems/remmina-nx.png  See also original at https://nomachine.com/ |
| remmina-sftp | SFTP protocol Icon | Main Window, Profile editor, Connection Window/Tab. | https://github.com/FreeRDP/Remmina/blob/next/remmina/icons/22x22/emblems/remmina-sftp.png |
| utilities-terminal stock desktop icon | SFTP protocol Icon | Main Window, Profile editor, Connection Window/Tab. | https://wiki.gnome.org/Attic/GnomeArt/Tutorials/IconThemes#Applications |

## Toolbar Icons

| Icon | Description | Context | Source |
|--------------------------------------------------------------------------------------------------------------------------|----------------------|------------------------|--------------------------------------------------------------------------------------------------|
| remmina-dynres | Dynamic Resolution | Main Connection Window | https://github.com/FreeRDP/Remmina/blob/next/remmina/icons/22x22/actions/remmina-dynres.png |
| remmina-fit-window | Resize to fit window | Main Connection Window | https://github.com/FreeRDP/Remmina/blob/next/remmina/icons/22x22/actions/remmina-fit-window.png |
| remmina-fullscreen | Full Screen | Main Connection Window | https://github.com/FreeRDP/Remmina/blob/next/remmina/icons/22x22/actions/remmina-fullscreen.png |
| remmina-scale | Scale Window | Main Connection Window | https://github.com/FreeRDP/Remmina/blob/next/remmina/icons/22x22/actions/remmina-scale.png |
| remmina-switch-page | Switch TAB | Main Connection Window | https://github.com/FreeRDP/Remmina/blob/next/remmina/icons/22x22/actions/remmina-switch-page.png |

## Panel Icons

The one showed in the desktop toolbar/taskbar/notifications areas

image

The icons are here:

- Light theme
- Dark theme 

All the other icons are stock icons https://developer.gnome.org/libgnomeui/stable/libgnomeui-gnome-stock-icons.html 

If I'm missing anything let me know

@elioqoshi @giox069

**Comment by elioqoshi** [comment]
@antenore , thank you! This is very indepth :)
I'm trying my hands on this right now

**Comment by elioqoshi** [comment]
I am no supporter of Job posts on the forum honestly. If a conversation happens here, it's appropriate UX. It doesn't make much sense to have a GitHub page post a PR to GitHub but have the conversation on another platform which is Discourse. I find it unintuitive. Sure, if there are folks who don't feel comfortable with GitHub, Discourse is a nice addition, but that shouldn't be best practice.

**Comment by jancborchardt** [comment]
We discussed this at the Open Source Design summit. We have the huge problem that it’s not visible whether a job is being worked on, or what the outcome was. Hence we discussed and decided on connecting Discourse to the website for that reason. cc @simonv3 @evalica

**Comment by elioqoshi** [comment]
That's an infrastructure problem not a people problem. If the tools are not there, why do people need to adopt to the tools? What you are saying is basically "Move the conversation somewhere else, although you seemed to have wrapped work up pretty well here already". Discourse has low traction for these discussions and the way to encourage those shouldn't happen in this way.

**Comment by antenore** [comment]
I agree with @elioqoshi , nevertheless if really needed, I can come down to a compromise, like keeping a log on discourse if you really need. But still, I'm just a customer, so just let me know.

**Pull request merged**
