### PR TITLE
New Job - UX/UI Designer Internship

### PR DESCRIPTION
**Pull request by staticmanapp**
Dear human,

Here's a new entry for your approval. :tada:

Merge the pull request to accept it, or close it to send it away.

:heart: Your friend [Staticman](https://staticman.net) :muscle:

---
| Field        | Content                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          |
| ------------ | ---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- |
| status       | searching                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        |
| date_posted  | 2018-03-13                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       |
| layout       | post                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             |
| organization | Zamphyr                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          |
| org_url      | https://zamphyr.com                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              |
| title        | UX/UI Designer Internship                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        |
| role         | 'UX', 'UI'                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       |
| compensation | gratis                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           |
| description  | Zamphyr Internship Program is an opportunity to be a part of a revolutionary startup set out to change technology education as we know it. You will be working on open-source technologies in education, improving our platform and spreading the vision of universal educational change to people and developer communities.

This internship is an unpaid, remote, project-based program, lasting 3 months (up to 6 months if required by accepted interns). Accepted interns work part-time (20 hrs/week) on projects or initiatives with mentors. Internship is remote and we give each intern an important part of the ecosystem through the project. The program is international and a great opportunity to meet new friends from all around the world. We use Slack, Zoom, Gitlab, Trello and Google Docs for the best remote workflow.

Our capacity for this program is very limited, and it is most likely that we will pick only one candidate for each position offered. Applicants will be evaluated for their past achievements, ideas and culture fit.

You can read about previous intern experiences: https://blog.zamphyr.com/interns-experience-from-zamphyr-to-gitlab-44b9fede6c6e?utm_source=google&utm_medium=form&utm_campaign=zia |
| deliverables |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  |
| how_to_apply | https://docs.google.com/forms/d/e/1FAIpQLSddMfaFAMteNlRyZwcSD-dGG8Wq5mD07IN0Jmp_DDMVE80QQw/viewform,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             |
| tags         | comment-subscription                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             |
| date         | 2018-03-13T22:32:47.814Z                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         |
| message      |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  |

### CODE REVIEW

**Comment by ei8fdb** [comment]
Firstly - I personally disagree with unpaid intern positions.

Secondly, no information about skills required, what the intern would be workin on.

I'm unsure about this. Others?

**Comment by m1guelpf** [comment]
Not sure what to do with this. @simonv3 wdyt?

**Comment by evalica** [comment]
Not really sure what "Zamphyr is going to be a open source school" means. 
They have this repo https://github.com/zamphyr but not very many contributors. 
We have also gratis jobs, so gratis internships for me is pretty much in the same category. 
For me this looks ok.

**Comment by ei8fdb** [comment]
> We have also gratis jobs, so gratis internships for me is pretty much in the same category.

Yes, and this is why I was unsure. My dislike for unpaid internships is when the organisation providing the internship gains more than the student/intern.

To "protect" the intern, I'd like to see more explanation of what they will be doing. Giving more information, will also make it more interesting to  to potential applicants.

Can we ask them to provide more information about what they will be working on/skills they will gain?

**Comment by m1guelpf** [comment]
ping @marxo as he seems to be the owner of the GitHub organization.

**Comment by marxo** [comment]
Thanks @m1guelpf I didn't know that this goes to Github 😆 CC @ei8fdb @evalica 

So, Zamphyr is basically dual-licensed (much like Gitlab for example). The content itself is licensed under CC0, a part of the platform is proprietary, while other open parts (we call that federation) is usually under MIT or other permissive licenses. One example of the latter is: https://gitlab.com/zamphyrhq/metrik

During our internship program, interns work only on the open-source part of things. I'm personally against unpaid labor so we don't have interns work on the proprietary part of the platform, and we try to provide value for them by using our HCI/UX expertise while helping them build something that is useful for everyone.

We don't put any firm requirements for interns because we feel like their hobby or past work speaks volumes for them. For this particular position (UX/UI Design Intern), interns will have a chance to go through things like Storyboarding, User Research, mapping of information architecture, A/B tests, Wireframing, accessibility initiatives, localization initiatives, grid systems, design systems and visual design.  And example of a previous project for design interns would be: http://open.zamphyr.com

**Comment by simonv3** [comment]
If we have unpaid work, I don't see why not.

**Comment by marxo** [comment]
@simonv3 Do you have a process defined for that since I'm not the PR author? The PR is now merged but the job is not on the website.

Thanks

**Comment by simonv3** [comment]
Hey @marxo, the PR hasn't been merged yet, it's still open :)

You can edit the file by clicking on "Files Changed" at the top, which will let you see the proposed changes:
screenshot from 2018-03-15 13-58-37

In the top right corner of that page you'll see the pencil button, which you can click on to edit the file that this PR is adding.
screenshot from 2018-03-15 13-58-26

When you make the changes it'll ask you whether you want to create a new branch or commit directly to the branch (I think, I'm not sure on how these permissions play out). commit directly to the branch is the easiest option, but both should work.

**Comment by marxo** [comment]
@simonv3 Ah, I see. The problem with these permissions is that I don't have push access so it doesn't allow me to change anything (I guess organization member have more permissive settings).

now

**Comment by simonv3** [comment]
Ah bummer! Well, I can merge the file, and you can do a PR the classic way (through a fork?)

**Comment by marxo** [comment]
@simonv3 I've sent the PR https://github.com/opensourcedesign/jobs/pull/300, please check if the metadata is valid.

**Pull request merged**
