### PR TITLE
2016-06-28-Patchwork-logo.md

### PR DESCRIPTION
**Pull request by stephenfin**

### CODE REVIEW

**Comment by elioqoshi** [comment]
Thanks Stephen! Here are 2 proposals by me :)

patchwork-01
patchwork-02

**Comment by stephenfin** [comment]
@elioqoshi That was quick - thanks for the merge and the suggestions. I prefer the second one, as the first sends the wrong message :wink: I would opt for a different color though: UPS are the only organization that can pull that off heh

**Comment by elioqoshi** [comment]
@stephenfin Sure, what color would you like to use?

**Comment by stephenfin** [comment]
@elioqoshi To paraphrase Henry Ford, I'll have any color so long as it's not brown. What would yo recommend? I tend to like greens and purples, but I have no real experience with color theory or similar arts.

**Comment by elioqoshi** [comment]
Henry was a smart guy :)

Here is a version in teal/blue. What do you think?

patchwork-01
patchwork-02

**Comment by stephenfin** [comment]
@elioqoshi Very nice, and a much improved color :smile: However, while I don't want to ask too much (especially when this is gratis), I wonder if it's giving the right message? The logo picks up on the patchwork name, but it doesn't allude to the purpose of the tool. Is this necessary? If not, then I'll simply wait for some other input. If so though, there are also some other points worth noting that I will add to the job:

* [Diff files](https://www.gnu.org/software/diffutils/manual/html_node/Example-Unified.html#Example-Unified) are used extensively in the tool. Patches add or subtract code
* Patchwork caputures a "conversation" between developers
* Patchwork is generally used for Linux-based projects (where mailing list workflows are common)

**Comment by jk-ozlabs** [comment]
I like @elioqoshi 's latest proposals, particularly the first with the white background. I don't think it necessarily needs to have a detailed representation of the project, but the simplicity of representing a 'patch' works for me.

**Comment by stephenfin** [comment]
Success. If @jk-ozlabs is happy with this then so am I. In that case, how could we proceed here @elioqoshi? I assume we'd need to get copyright and source files from you?

**Comment by elioqoshi** [comment]
@stephenfin yes sure, sending you the files today

**Comment by elioqoshi** [comment]
@stephenfin @jk-ozlabs here we go:
http://elioqoshi.me/owncloud/index.php/s/fGzawZuitvruuXx

**Comment by zaverichintan** [comment]
Wow Amazing it is

**Comment by stephenfin** [comment]
@elioqoshi Any chance of getting a new link to those images? 😄

**Comment by elioqoshi** [comment]
@stephenfin yeah sure, I will be able to next week as I'm traveling now. Didn't you download them before?

**Comment by stephenfin** [comment]
Of course - you're speaking at FOSDEM, right? I'm also attending (and speaking on Patchwork).

I downloaded them but they seem to have lost to the ether some time in the past few months. I'll be sure to archive them next time round.

________________________________

**Pull request merged**
