### PR TITLE
Rename ComposerCI to DependenCI

### PR DESCRIPTION
**Pull request by m1guelpf**
We changed name!

### CODE REVIEW

**Comment by elioqoshi** [comment]
@m1guelpf so you need an updated logo I guess?

**Comment by m1guelpf** [comment]
@elioqoshi The logo is awesome! The name is still *CI so the logo can keep being the same. I only need a change in the text, to have the new name instead of the old one :wink:

**Comment by elioqoshi** [comment]
@m1guelpf Okay then, will do

**Comment by m1guelpf** [comment]
@elioqoshi Could you upload the logos to the organization?

**Comment by elioqoshi** [comment]
@m1guelpf Yes but I don't have time until end of next week. Please ping me again

**Comment by m1guelpf** [comment]
@elioqoshi Pinged!

**Comment by m1guelpf** [comment]
@elioqoshi Perfect. Can you upload it to the repo?

**Comment by elioqoshi** [comment]
Sorry, traveling and cannot those days. Please feel free to do it or ask some fellow designer for help :/

**Comment by m1guelpf** [comment]
@elioqoshi I don't know how to do that... could you explain me how to do that/link to a tutorial or tell me when you'll finish traveling? Thank you!

**Comment by elioqoshi** [comment]
Just came back, I can do it this week, ping me again tomorrow if I forget :D

**Comment by AnXh3L0** [comment]
Hello @m1guelpf, I just uploaded the files in the repo, here is the [link](https://github.com/uracreative/works/tree/master/DependCI)

**Comment by m1guelpf** [comment]
@AnXh3L0 Thank you very much! I am on a plane now, but will move them to our repo as soon as I land.

**Comment by m1guelpf** [comment]
@AnXh3L0 @elioqoshi Moved to the branding repo, thank you!

**Pull request merged**
